NVIDIA/apex

.gitignore, apex/amp/README.md, apex/amp/__init__.py, apex/amp/amp.py, apex/amp/handle.py, apex/amp/lists/functional_overrides.py, apex/amp/opt.py, apex/amp/scaler.py, apex/amp/utils.py, apex/amp/wrap.py, build_cffi.py
Big overhaul of the amp API, described in the updated README. Top items:
1. Main function now called `amp.init()` with a boolean argument `enabled` that allows a pass-through mode when set to false. Useful for writing, eg, `amp_handle = amp.init(enabled=args.amp)` and then not needing if statements anywhere.
2. Support for explicit optimizer wrapping: `optimizer = amp_handle.wrap_optimizer(optimizer)`. The wrapper supports the `loss_scale()` context manager. Enables use w/ multiple optimizers.
3. Support for multiple backward passes per-step with `num_loss` argument to `wrap_optimizer()`.
4. Improved annotations and registration functions for handling backend code in a less fragile way.
The other big change is a refactoring of optimizer wrapping / loss scaling code to split it all out …
=> amp API update

csrc/scale_cuda.cu, csrc/weight_norm_bwd_cuda.cu, csrc/weight_norm_fwd_cuda.cu
Build was breaking against upstream PyTorch. Could have just changed the header to the local `CUDATypeConversion.cuh` but decided to keep things consistent with the ustream PR.
=> Adding changes due to https://github.com/pytorch/pytorch/pull/8660

apex/parallel/distributed.py
This fixes an issue in `flat_dist_call`, which leads to a deadlock of processes. The issue is due to processes cycling over tensor types in different orders and calling non matching collective operations in the body of the cycle.
=> Fixed deadlock issue

apex/fp16_utils/fp16_optimizer.py, apex/parallel/distributed.py
Previously, the check would fail to catch if a parameter was removed from the end of module.parameters(), but no other ordering changes occurred.
@csarofeen 
Also removed unnecessary if statement in closure handling for dynamic loss scaling.
=> More stringent check for parameter changes to trigger refresh of distributed

examples/imagenet/main.py, examples/imagenet/main_fp16_optimizer.py
In the validate routine, the reduced precision values (reduced_prec1 and reduced_prec5) are not reported. Instead, the unreduced prec1 and prec5 are reported. Additionally, there are no guards against reduction calls when not running distributed (as there are in the train routine) which causes an error.
I have changed the validate routine to match the handling of these variables from train.
=> Fixes to validation in imagenet example scripts.

apex/fp16_utils/fp16_optimizer.py, apex/parallel/LARC.py
* Proper implementation of LARC clipping
* Documentation of LARC class
* Modification of FP16_Optimizer to absorb optimizer instance that's being wrapped instead of creating new optimizer instance of same class.
=> LARC clipping+documentation

apex/amp/amp.py, apex/amp/handle.py, apex/amp/test/test_basic_casts.py, apex/amp/test/test_promotion.py, apex/amp/test/test_rnn.py, apex/amp/test/utils.py, apex/amp/utils.py, apex/amp/wrap.py
Main change here is the first set of unit tests for amp. Tests all the different casting cases. Tests for things like loss scaling or the optimizer wrapper are still TODO.
Also adds experimental support for calling `handle._deactivate()` on an initialized amp handle -- it unwinds all monkey patching. This makes test running easier.
Run `python -m unittest discover -v` in the apex root directory to run tests.
=> amp unit tests

apex/amp/amp.py, apex/amp/rnn_compat.py, apex/amp/test/test_rnn.py, apex/amp/utils.py, apex/amp/wrap.py
Adds code to handle casts for the Aten-based RNN API, along with compatibility logic to continue working with 0.4.
Tests so far are:
- RNN unit tests (added an extra one here to check the padded sequence logic)
- Check training curves match on word-lm example w/ amp enabled
=> amp support for Aten RNNs

examples/imagenet/README.md
Default static loss scale of 1.0 (default value) for resnet50 doesn't converge. Either remove example or put static loss scale 128 on it, which is known to converge well.
=> Remove some fp16 examples that don't converge

apex/parallel/distributed.py, examples/imagenet/main.py, tests/distributed/ddp_race_condition_test.py, tests/distributed/run_race_test.sh
Comprehensive rework of Apex DDP that significantly improves performance overlapping communication and computation on networks with a high ratio of CPU utilization to GPU utilization (e.g. resnet50 with a small batch size).
=> Efficient bucketing

examples/FP16_Optimizer_simple/closure.py, examples/FP16_Optimizer_simple/distributed_apex/distributed_data_parallel.py, examples/FP16_Optimizer_simple/distributed_apex_legacy_launcher/distributed_data_parallel.py, examples/FP16_Optimizer_simple/distributed_pytorch/distributed_data_parallel.py, examples/FP16_Optimizer_simple/minimal.py, examples/FP16_Optimizer_simple/save_load.py, examples/distributed/main.py, examples/imagenet/main.py, examples/imagenet/main_fp16_optimizer.py, examples/imagenet/main_reducer.py, examples/word_language_model/generate.py, examples/word_language_model/main.py, examples/word_language_model/main_fp16_optimizer.py, examples/word_language_model/model.py
This PR updates the examples to PyTorch versions >= 0.4.0.
Minor cleanups were performed in all examples:
- Remove `Variables` as they are deprecated
- Remove `torch.cuda.manual_seed`, since `torch.manual_seed` also seeds all CUDA devices if available ([source](https://pytorch.org/docs/master/notes/randomness.html#pytorch))
- Add `with torch.no_grad()` statements where they were missing or `Variable(, volatile=True)` was used
Minor potential bugs fixed:
- [`examples/distributed/main.py`](https://github.com/ptrblck/apex/blob/28bdc04eec8304c4985bb6625828f3c8fdaf321e/examples/distributed/main.py#L178): Convert `correct` to `float`, since `torch.tensor.eq` op returns a `torch.uint8` tensor, which might overflow for large batch sizes
- …
=> Update examples to PyTorch >=0.4.0

apex/amp/utils.py, apex/parallel/distributed.py, tests/run_amp/test_cache.py
The caching logic is still vulnerable to the user manually modifying weights between eval and training:
```
with torch.no_grad():
forward # validation pass, may cache some casts
...user manually modifies weights in some way that the cache cannot detect...
forward # uh oh, this will use stale cached values that do not reflect the manual changes...
backward # this will drop the cache
forward # this will refresh the weights, and everything will be ok from here
```
However, this vulnerability was also present with the old caching logic.
I think the only permanent solution is to drop the cache at the end of forward instead of the end of backward (which can be done if we wrap the model like you said, which gives us some leeway to wrap forward).
=> Fix + tests for the eval->training caching issue

examples/word_language_model/README.md, examples/word_language_model/data.py, examples/word_language_model/main.py, examples/word_language_model/main_fp16_optimizer.py
Currently, apex/examples/word_language_model uses the same default hyperparams as the official Pytorch word_language_model example.  The dimensions of the resulting GEMMs internal to the model are not multiples of 8 in some cases, preventing Tensor Core use.
This PR updates apex/examples/word_language_model to use Tensor Core-friendly GEMM dimensions, and provides more instructions and general guidance on doing so.
=> Update default dims in word_language_model to be multiples of 8 to enable Tensor Core use

apex/optimizers/fp16_optimizer.py
Add state_dict() and load_state_dict() for apex.optimizers.FP16_Optimizer to store and recover optimizer states. These two methods are important to recover from a stored training checkpoint.
=> apex.optimizers.FP16_Optimizer: add state_dict() and load_state_dict()

apex/fp16_utils/__init__.py, apex/fp16_utils/fp16util.py, tests/run_fp16util/test_fp16util.py, tests/run_test.py
This commit adds an FP16Model class as a successor to `network_to_half()`.
The benefits of this class are:
- Preservation of single-precision for BatchNorm layers. The models
generated by `network_to_half()` convert BatchNorm moment tensors to
half-precision, then back to single-precision, which hurts the
accuracy of the moment estimators and occasionally results in NaNs.
- Support for multi-argument `nn.Module`s (self-explanatory from code).
=> Better FP16 support in pytorch fp16 utils.

apex/parallel/optimized_sync_batchnorm.py, apex/parallel/sync_batchnorm.py
Update primitive implementation with a dummy argument channel_last
apex.parallel.convert_syncbn_model now support both SyncBatchNorm implementation
This resolves #166
=> update SyncBatchNorm API

csrc/welford.cu
The existing "next power of 2" implementation produces incorrect results in some cases. The one identified so far is that for every value less than a power of 2 by 1 keeps value the same, e.g. h_next_pow2(7) produces 7, etc. For numbers farther away, the output is correct, e.g. h_next_pow2(26) gives 32.
The fix is identical to the "popular" way of doing this, i.e. subtracting 1 before the bit shifts, doing bitwise ORs with the bit-shifted values, and then adding 1 again, as in [here](https://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2) for instance.
Note that the [earlier commit](https://github.com/NVIDIA/apex/blame/8bd382fadd42f77922fbc3dfacc3e4cc2f89ece5/csrc/welford.cu#L22:L29) was also wrong because it didn't subtract 1 at the beginning.
=> Bug fix in next power of 2

apex/amp/opt.py
Adds missing argument to `LossScaler`.
Would fix #183 
Alternative would be to make this a default argument in the scaler.
=> Add "dynamic" argument to loss scaler

csrc/fused_adam_cuda_kernel.cu, csrc/layer_norm_cuda_kernel.cu, csrc/multi_tensor_scale_kernel.cu, csrc/welford.cu
Effectively reverts https://github.com/NVIDIA/apex/commit/42180bd929639c137706be99c93626da93a36f2e, because once upstream merges https://github.com/pytorch/pytorch/pull/17996, the shim hack for type-based dispatch in extensions will no longer be necessary (and in fact will break).  However, with current upstream master, the shim hack is still necessary, so I can't merge this into Apex master until 17996 is merged upstream.
=> Anticipating upstream #17996

apex/amp/_initialize.py
Allow more permissive inputs to forward function:
(1) When some input is a CPU pytroch tensor, show a one-time warning instead of printing it every time the forward function is called.
(2) Allow numpy arrays as (nested) inputs. Currently this fails.
=> More permissive inputs to forward function

csrc/layer_norm_cuda.cpp, csrc/layer_norm_cuda_kernel.cu
`IntList` has been deprecated by https://github.com/pytorch/pytorch/commit/4404762d7dd955383acee92e6f06b48144a0742e#diff-ff8fdb5222085eb1036fbebb7cc4f4a9
This PR should resolve some build warnings.
=> Rename IntList to IntArrayRef

apex/amp/lists/torch_overrides.py
This is to fix the following error:
File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
input = module(input)
File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 722, in forward
return F.prelu(input, self.weight)
File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1040, in prelu
return torch.prelu(input, weight)
RuntimeError: expected scalar type Half but found Float
=> Add prelu to list of torch overrides

apex/parallel/optimized_sync_batchnorm.py, apex/parallel/optimized_sync_batchnorm_kernel.py, apex/parallel/sync_batchnorm.py
supporting 2 dimensional input, resolving issue #194
Implementation:
for 2d input, switching channel_last flag to true for better memory access
pattern in the kernel.
=> [SyncBatchNorm]

apex/amp/handle.py
Prints
```bash
Gradient overflow.  Skipping step, loss scaler 3 reducing loss scale to 32768.0
````
instead of 
```bash
Gradient overflow.  Skipping step, loss scaler {} reducing loss scale to 3
```
=> fix: minor print typo

apex/parallel/optimized_sync_batchnorm_kernel.py
in line 54, running_var should be running_variance..
=> Fix a typo in optimized_sync_batchnorm_kernel.py

apex/amp/__init__.py, apex/amp/_amp_state.py, apex/amp/_initialize.py, apex/amp/_process_optimizer.py, apex/amp/frontend.py, apex/amp/handle.py, apex/amp/scaler.py, apex/fp16_utils/fp16_optimizer.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_axpby_kernel.cu, csrc/multi_tensor_scale_kernel.cu, docs/source/advanced.rst, docs/source/amp.rst, tests/L0/run_amp/test_cache.py, tests/L0/run_amp/test_multi_tensor_axpby.py, tests/L0/run_amp/test_multiple_models_optimizers_losses.py, tests/L1/common/compare.py, tests/L1/common/run_test.sh, tests/L1/cross_product/run.sh, tests/distributed/amp_master_params/amp_master_params.py, tests/distributed/amp_master_params/compare.py, tests/distributed/amp_master_params/run.sh
Handle arbitrary combinations of optimizers/models/losses.  Do not maintain a loss scale per optimizer.  Instead, maintain either a single global loss scale (by default), or a loss scale per-loss (if the user supplies the `num_loss` argument to amp.initialize and the `loss_id` argument to each invokation of amp.scale_loss).
Current status:  L0 tests have been added and are passing (maybe need more).  L1 single-GPU tests pass.  Verified that it fixes Szymon's issue with master params getting out of sync across processes for JoC GNMT.  L1 multi-GPU tests underway.
=> WIP:  Handle arbitrary combinations of optimizers/models/losses

apex/amp/lists/functional_overrides.py
Running interpolation (nearest neigbor and bilinear) in fp16 is slower than fp32, because the backprop depends on individual half atomicAdds (as opposed to half2 atomicAdds), which actually translates to atomicCAS under the hood. For networks that heavily depend on upsampling (any kind of generative CV models, say GANs), the overall impact of using fp16 upsampling results in up to 30% end-to-end training slowdowns. 
The long-term fix is to fix upsampling (I'm planning to make PRs to this effect), but for now I think it's better to run upsampling in fp32 instead.
=> Run interpolation in fp32 because it's faster

apex/normalization/fused_layer_norm.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py, tests/L0/run_test.py
As discussed in #239, here is a quick fix to that issue while waiting to move the module upstream to pytorch.
=> quick fix: make FusedLayerNorm compatible with cpu

apex/amp/lists/torch_overrides.py
prelu belongs in FP16_CASTS
The main use of these functions (e.g.: `torch.{conv*, prelu}`) is via their `torch.nn`
wrapping layers.
The `torch.nn` layers are what contain the weights and call into these lower level
functions with the weights as a parameter in their `forward()` method.
The `torch.conv*` functions are already in the `FP16_CASTS` list due to amp's philosophy of
casting the parameters rather than the model/layer weights.
Conceptually `torch.prelu` is the same as the `torch.conv*` case, where its weight parameter
is passed in from its wrapper layer `torch.nn.PReLU`.
=> prelu belongs in FP16_CASTS

apex/amp/_initialize.py
If a model on the CPU was passed to `amp.initialize`, a `RuntimeError` was thrown stating `model.half()` shouldn't be called.
This PR splits the error message into the `model.half()` part and the non-CUDA parameter part and gives a better error description to the user.
=> Add CUDA warning to check_params_fp32

apex/amp/_initialize.py
Fix `check_optimizers` using `bad_optim_type` and move the check up so that it the appropriate error will be thrown.
Currently passing an instance of `FP16_Optimizer` will trigger the `else` statement [here](https://github.com/NVIDIA/apex/blob/28097c9999d86bd889a1f03c963e29e3384f3996/apex/amp/_initialize.py#L151), so that the error might be confusing stating "optimizers must be either a single optimizer or a list of optimizers."
=> move and fix check_optimizers

csrc/fused_adam_cuda_kernel.cu, csrc/layer_norm_cuda.cpp, csrc/layer_norm_cuda_kernel.cu, csrc/multi_tensor_l2norm_kernel.cu, csrc/multi_tensor_scale_kernel.cu, csrc/type_shim.h, csrc/welford.cu
Fixes #267 
PyTorch PR https://github.com/pytorch/pytorch/pull/17991 introduced some breaking changes which broke building `apex` using PyTorch master.
This PR replaces all deprecated `.type().ScalarType()` calls with `.scalar_type()` as well as `at::ScalarType::Type` with `at::kType`.
=> Replace type().ScalarType() with scalar_type()

apex/contrib/csrc/groupbn/batch_norm.cu, apex/contrib/csrc/groupbn/batch_norm.h, apex/contrib/csrc/groupbn/batch_norm_add_relu.cu, apex/contrib/csrc/groupbn/batch_norm_add_relu.h, apex/contrib/csrc/groupbn/cuda_utils.h, apex/contrib/csrc/groupbn/interface.cpp, apex/contrib/csrc/groupbn/ipc.cu, apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h, apex/contrib/groupbn/__init__.py, apex/contrib/groupbn/batch_norm.py, apex/parallel/optimized_sync_batchnorm.py, apex/parallel/optimized_sync_batchnorm_kernel.py, csrc/syncbn.cpp, csrc/welford.cu, setup.py
Persistent group batchnorm added
Added persistent grouped batch norm for performance run on strong scaling case:
currently only supporting:
1. nhwc layout
2. fp16
3. synchronization only within a node!
Potential issue: relying on unstable internal `_share_cuda_()` to get ipc mem handle.
Environment variable is used to tune LAUNCH_MARGIN that limits the CTAs usage
by the persistent kernel.
Documentation and examples will follow.
* Also fused BNAddRelu for apex::parallel::SyncBatchNorm nhwc kernel.
=> Bnp integration pr

examples/deprecated_api/imagenet/main.py, examples/deprecated_api/imagenet/main_amp.py, examples/deprecated_api/imagenet/main_fp16_optimizer.py, examples/deprecated_api/imagenet/main_reducer.py, examples/imagenet/main_amp.py, tests/L1/common/main_amp.py
PR removes unused `tens` tensor in all occurrences of `fast_collate`.
=> Remove unused tensor in fast_collate

apex/contrib/csrc/xentropy/interface.cpp, apex/contrib/csrc/xentropy/xentropy_kernel.cu, apex/contrib/test/test_label_smoothing.py, apex/contrib/xentropy/__init__.py, apex/contrib/xentropy/softmax_xentropy.py, setup.py
@jjsjann123 @mcarilli 
This PR contains softmax cross entropy loss function with label smoothing support, which will reduce memory usage and improve performance.
A brief unittest results:
```
$ python test_label_smoothing.py        
Max atol idx: 246645668, diff: 0.000001, ref: 0.001428, tst: 0.001429 
Max atol idx: 289230632, diff: 0.000001, ref: 0.001148, tst: 0.001149 
Max atol idx: 60159214, diff: 0.000002, ref: 0.001976, tst: 0.001978  
Max atol idx: 87538934, diff: 0.000001, ref: 0.001067, tst: 0.001066  
Max atol idx: 107560465, diff: 0.000001, ref: 0.001181, tst: 0.001180 
Max atol idx: 35533876, diff: 0.000001, ref: 0.001122, tst: 0.001122  
Max atol idx: 17088608, diff: 0.000001, ref: 0.001122, tst: 0.001122  
Max atol idx: 69708634, diff: 0.000001, ref: 0.001080, tst: 0.001081 …
```
=> Add softmax cross entropy loss with label smoothing support.

apex/parallel/distributed.py
Fixes minor errors in the URLs for [apex.parellel](https://nvidia.github.io/apex/parallel.html) pointing to old source code locations.
=> fix URLs in docs of apex.parallel

apex/optimizers/fp16_optimizer.py
Since gradient overflow is a normal part of dynamic loss scaling until the right loss scaling is established, it seems appropriate to gate the print statements with the 'verbose' parameter.
In distributed training, with dozens of processes all printing 'Grad overflow...' to the log, it can be tedious to scroll past. In this setting the verbose=True can be reserved for the process with world rank 0.
=> use verbose parameter to control print of grad overflow

apex/amp/frontend.py
Fixes #320 
`keep_batchnorm_fp32` is undefined in [this line of code](https://github.com/NVIDIA/apex/blob/c490bd368faafb19986f857f9baa145d30872e92/apex/amp/frontend.py#L81). Use `value` instead to rais the proper error message.
=> Use `value` in assert statement for keep_batchnorm_fp32

setup.py
The warning message was too subtle/too easy to overlook in the output of setup.py, and it really should be a hard error.
Making it a hard error should also assist with cuda _driver_ version errors like https://github.com/NVIDIA/apex/issues/314.  https://github.com/NVIDIA/apex/issues/314 resulted because the cuda _driver_ (libcuda.so) version was 10.0, the cuda _toolkit_ version used to compile the Pytorch binaries was 10.0 (which was fine), but the cuda _toolkit_ version used to compile Apex was 10.1** (which triggered a PTX JIT compilation error at runtime because the 10.0 libcuda.so couldn't handle the PTX produced by the 10.1 nvcc).  The PTX JIT compilation error message was cryptic and unhelpful.
However, if the _toolkit_ version that was used to compile _Pytorch_ binaries is too …
=> Hard error on mismatch between torch.version.cuda and + the Cuda toolkit version being used to compile Apex

csrc/multi_tensor_lamb_stage_1.cu, csrc/multi_tensor_lamb_stage_2.cu
This implementation of LAMB is a few % faster than the first one.
=> Separate LDG/STG from compute loop

apex/amp/_initialize.py
Fix for https://github.com/NVIDIA/apex/issues/363.
There's a tradeoff here:
This version (giving the `to` method lower priority than Tensors, string_classes, and numpy.ndarrays) will ignore a custom `to` method if the custom batch is an instance of string_classes or numpy.ndarray.  
However, if we give the custom `to` method higher priority, it might be spuriously called if one of the string_classes or numpy.ndarray has a `.to` method already.
A third option is to force user-defined `to` method to have a more unique name, like `to_amp_type`.  But this would require changing the existing code.
@felix-schneider do you see a strong reason to prefer one of these options?
=> Give custom to method a higher priority

csrc/fused_adam_cuda.cpp
We plan to remove the implicit semicolon from one of our macros, this will prevent breakage in that case.
Signed-off-by: Edward Z. Yang <ezyang@fb.com>
=> Add missing semicolon.

apex/normalization/fused_layer_norm.py
Per the recently-added warning: https://github.com/pytorch/pytorch/blob/fdfc676eb6c4d9f50496e564976fbe6d124e23a5/torch/csrc/autograd/python_function.cpp#L636-L638
=> Update FusedLayerNorm for new function API

examples/dcgan/README.md, examples/dcgan/main_amp.py
This PR adds a DCGAN example modified from the official DCGAN PyTorch example.
`opt_levels` `O1` and `O2` were tested and create visually similar outputs.
=> Add DCGAN example

apex/amp/frontend.py, tests/L0/run_mixed_adam/test_fp16_optimizer.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/NVIDIA/apex on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./apex/amp/frontend.py:34:21: F821 undefined name 'self'
if k in self.options:
^
./apex/amp/frontend.py:35:17: F821 undefined name 'self'
self.options[k] = v
^
./tests/L0/run_mixed_adam/test_fp16_optimizer.py:133:19: F821 undefined name 'os'
script_path = os.path.dirname(os.path.realpath(__file__))
^
./tests/L0/run_mixed_adam/test_fp16_optimizer.py:133:35: F821 undefined name 'os'
script_path = os.path.dirname(os.path.realpath(__file__))
^
./docs/source/conf.py:210:5: F821 undefined name 'List'
^
./docs/source/conf.py:210:5: F821 undefined name 'unicode'
^
./docs/source/conf.py:210:5: F821 undefined name 'Tuple'
^
7 …
```
=> Don't forget self in Properties._update_options_dict()

apex/amp/utils.py
PyTorch PR removed `backend.FunctionBackend` in this PR:
https://github.com/pytorch/pytorch/commit/23fde77d3d14c1e3582ac1f8c1456b4f59a242d1
Issue reported in #460 
Thanks @labor00 for reporting!
=> remove deprecated backend.FunctionBackend calls

apex/amp/lists/torch_overrides.py, apex/amp/utils.py
* fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/802
/cc @yiColddrink somehow I didn't have to touch these lines:
```py
if version_num < 1.1:
FP32_FUNCS.append('mean')
```
=> fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/802

tests/L0/run_amp/test_checkpointing.py
Increased `atol` to `1.5e-4` due to failing `state_dict` comparison for `'O0'` and `'O2'`:
```python
x = torch.tensor(0.8839)
torch.allclose(x.half().float(), x, atol=1e-4)
> False
torch.allclose(x.half().float(), x, atol=1.5e-4)
> True
```
=> Disable tests for mixed opt_levels, add bitwise accurate test of parameters

README.md
The code example in the README, although meant to illustrate checkpointing, is the first `amp` usage example seen by a new user, and it looks so complete that it's tempting to just copy what's written there to adapt one's training script. Unfortunately, it misses the loss scaling, so a new user doing so will find that checkpointing works great, but training doesn't work at all. (Been there, done that.)
I'd propose to just add the two lines needed for loss scaling (this PR), or remove the code example completely so people will be forced to look at the documentation.
=> Include loss scaling in README code example

apex/__init__.py, apex/amp/_initialize.py, apex/amp/handle.py
=> allow for non-distributed envs (Windows)

apex/parallel/optimized_sync_batchnorm.py, tests/distributed/synced_batchnorm/test_batchnorm1d.py, tests/distributed/synced_batchnorm/unit_test.sh
enable channel_last flag when input to syncBatchNorm is 1d tensor. Fix #194, which was broken again in PR #275
=> fixing batchnorm 1d input

apex/amp/_amp_state.py
* Fixes #619 
* Determine whether in distributed mode at function call, not at module import
* Support other initializations of torch.distributed other than `env://`
=> Don't define distributed variable on module import

apex/contrib/optimizers/fp16_optimizer.py, apex/contrib/optimizers/fused_sgd.py
Changes include:
1. For existing `apex.contrib.optmizers.FP16_Optimizer`:
* remove the `_flatten_dense_tensors step` and use `multi_tensor_apply` later
* use `multi_tensor_l2norm` instead of a for loop for nan check
2. Add `apex.contrib.optmizer.FusedSGD` for manual fp16. (Not designed to be used with AMP. Must be used with `apex.contrib.optmizers.FP16_Optimizer` altogether)
=> updated apex.contrib.optimizers.FP16_Optimizer and FusedSGD

examples/dcgan/README.md
Actual flag is --opt_level and copy pasting the example results in an unrecognized arguments error.
=> Fix opt_level command line arg in instructions.

csrc/multi_tensor_apply.cuh, setup.py, tests/L0/run_amp/test_multi_tensor_axpby.py
@ngimel @VitalyFedyunin
This is only to unblock tests until the native integrations of [autocasting](https://github.com/pytorch/pytorch/pull/32140) and [gradient scaling](https://github.com/pytorch/pytorch/pull/33366) are merged.
As far as I can tell, grabbing data_ptr()s + numel()s from a list of nhwc-contiguous tensors and using them to launch the multi tensor apply kernel just works, as long as all the tensors that interact across lists are the same format.  For example, if you're adding two lists, this will be fine:
[nhwc0, nhwc1, nchw0, nchw1] +
[nhwc2, nhwc3, nchw2, nchw3] =
[result0, result1, result2, result3]
but this won't:
[nhwc0, nhwc1, nhwc2, nhwc3] +
[nchw0, nchw1, nchw2, nchw3] =
[result0, result1, result2, result3]
=> NHWC support for multi tensor apply

apex/pyprof/__init__.py, apex/pyprof/prof/__init__.py, apex/pyprof/prof/utility.py, tests/L0/run_pyprof_data/test_pyprof_data.py, tests/L0/run_test.py
This seems like a possibly naive fix for #601. This unblocked us when using pyprof, but it's not clear to me if it breaks other use cases.
=> Add support for bool datatype (#601)

apex/parallel/LARC.py
Add a `param_groups` property which passes the setter and getter calls to the internal optimizer.
Fixes https://github.com/NVIDIA/apex/issues/766.
=> Return internal optimizer's param_groups from LARC

apex/amp/_initialize.py, apex/amp/handle.py, apex/parallel/LARC.py, tests/L0/run_amp/test_larc.py
The LARC optimizer wraps an underlying optimizer and then needs to be passed
to amp.initialize for mixed precision. There were 3 different crashes happening
in this situation, fix all of them and add a unit test.
I don't know if the 'LARC' in sys.modules check ever worked. In my setup, the
entry in sys.modules is 'apex.parallel.LARC'. Checking if the variable is
defined seems more reliable though.
=> Fix LARC with mixed precision

apex/contrib/multihead_attn/self_multihead_attn_func.py
Fixes dropout scaling in backward pass of multihead attention
=> fix dropout scaling from p to 1/(1-p) in multihead attention

apex/contrib/csrc/xentropy/xentropy_kernel.cu
Increase default ILP so that each thread handle 16 Bytes data in one step
Make thread load/store longest vector possible
Support shift for blocks that are not aligned. Greatly improve performance for cases where `classes % 8 > 0`
=> Changes to make xentropysoftmax load/store vectorized when possible:

apex/optimizers/__init__.py, apex/optimizers/fused_adagrad.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_adagrad.cu, setup.py, tests/L0/run_optimizers/test_adagrad.py
This is an implementation of the standard Adagrad optimizer in Apex, mirroring the [`torch.optim.Adagrad`](https://pytorch.org/docs/stable/optim.html#torch.optim.Adagrad) baseline implementation.
Performance is substantially improved, especially for small models. Here, we compare the effective bandwidth achieved of `optim.step()` on a simple MLP as we vary the hidden dimension `N`
```.py
nn.Sequential(
nn.Linear(N, N),
nn.Linear(N, N),
nn.Linear(N, N),
nn.Linear(N, N),
nn.Linear(N, N),
nn.Linear(N, N),
nn.Linear(N, 1),
)
```
This supports the standard weight decay implementation, as well as an AdamW-style decoupled weight decay (disabled by default).
=> [Optimizers] apex.optimizers.FusedAdagrad implementation

apex/optimizers/fused_lamb.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_lamb.cu, csrc/multi_tensor_lamb_stage_2.cu
Changes include:
For `apex.optimizers.FusedLAMB`
- use global norm rather than per group norm in gradient clipping 
- add option for using "NVLAMB" (by setting `use_nvlamb`=True), which applies adaptive learning rate to all parameters (the default is to only apply to those with non-zero weight decay)
=> Use global gradient clipping in FusedLAMB & add option for using NVLAMB

apex/optimizers/fused_lamb.py
Simple fix a typo in LAMB optimizer when use O3 optimization level
=> Fixed a typo in LAMB optimizer with O3 mode

apex/optimizers/fused_lamb.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_lamb.cu, csrc/multi_tensor_lamb_stage_1.cu
Making FusedLAMB async: pass global norm by tensor directly into later kernel and get rid of `.item()`
=> make FusedLAMB async

README.md, apex/pyprof/nvtx/nvmarker.py, setup.py
Pyprof now has its own repo (https://github.com/NVIDIA/PyProf) and code should be removed from Apex soon.  In the meantime, add warnings that point to new repo.
=> Add Pyprof removal warnings that point to new repo

tests/L0/run_optimizers/test_lamb.py
Add reference LAMB implementation, which is a PyTorch equivalent to this TensorFlow addon
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/lamb.py + global grad norm clipping,
to test `FusedLAMB(use_nvlamb=True)`, i.e. apply adaptive learning rate to all parameters
=> add unit tests for FusedLAMB optimizer

apex/amp/compat.py, apex/amp/lists/tensor_overrides.py
Gives pytorch the liberty to remove some Tensor methods if desired (e.g. `__div__`, https://github.com/pytorch/pytorch/pull/39151)
Necessary as a stopgap to support existing scripts that use apex amp with recent pytorch.  Fix is not an endorsement of apex amp over [`torch.cuda.amp`](https://github.com/NVIDIA/apex/issues/818).  `torch.cuda.amp` is still 100% the best way forward.
Fixes errors with https://github.com/pytorch/pytorch/pull/39151 and Amp tests pass locally.
=> Don't patch tensor ops that aren't present  

apex/contrib/sparsity/asp.py
`name` is out of scope in the function `add_sparse_attributes`, `p_name` is the correct variable.
=> Fixed variable name

apex/contrib/multihead_attn/encdec_multihead_attn.py, apex/contrib/multihead_attn/self_multihead_attn.py
Fused weights were meant to be initialized just like un-fused counterparts. This PR fixes weight init by adding proper gain factors for nn.init.xavier_uniform_.
=> Fixed weight init for fused weight matrices in fused MHA by adding correct gain factor

apex/contrib/sparsity/asp.py
1. Support to include in sparse_parameter_list an user-supplied custom layer type and its parameter name. This is useful when users have their own implementation of nn.Linear or nn.Conv2D. For example, huggingface repo has a custom implementation of nn.Linear called LinearActivation.
2. Print info of layers in the model that are not pruned.
=> Asp sparse param dict update

setup.py
Should fix https://github.com/NVIDIA/apex/issues/931
Thanks @mcarilli for the review.
=> move sm80 code inside MHA

apex/parallel/optimized_sync_batchnorm_kernel.py
We'd like to revert https://github.com/pytorch/pytorch/pull/40573 upstream.  This PR ensures syncbn will be ready when we do (fixes @xwang233's repro after rebuilding with https://github.com/pytorch/pytorch/pull/40573's diffs reverted). @ngimel 
This should not be taken as an endorsement of apex syncbn over pytorch native syncbn.
=> Makes syncbn compatible with stricter collective size/stride checks in Pytorch

apex/parallel/optimized_sync_batchnorm_kernel.py, csrc/welford.cu
In this PR, we mainly tried to optimize the performance of Syncatchnorm and also fixed one potential issue in the welford_parallel kernel implementation.
1) For performance improvement, we batched the mean/var/count all_gather communication together and sent it once in the forward path
2) We also batch the all_reduce in backward path
3) We add the contiguous call on the input of welford_parallel kernel.
If there is any standard perf benchmark, I would be happy to run it.
=> Optimize the sync batchnorm by batching the communication

examples/imagenet/main_amp.py
- resume() is a nested function and when it loads best_prec1 it creates
a local variable that hides the one from the parent function. This
PR adds `nonlocal` to modify the parent function variable as intended
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>
=> Fix lack of proper loading of best_prec1 from the checkpoint

README.md
when `pip install -v` is used, it does a huge dump of all the pip urls it found, which is totally irrelevant from this build and makes it hard to see that the build actually worked or not. Adding `--disable-pip-version-check` solves this problem.
It replaces this:
```
Successfully installed apex-0.1
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Fetching project page and analyzing links: https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 14676
Found link …
```
=> remove pip-version-check noise that hides the outcome of the build

apex/contrib/sparsity/README.md
The Recipe was presented after some non-standard API calls, so moving the suggested usage up, giving it its own section, and reinforcing the suggested usage in the non-standard section.
=> Update ASP README to highlight default recipe

README.md, apex/amp/_amp_state.py
Nightly PyTorch has removed `container_abcs` from `torch._six`.
https://github.com/pytorch/pytorch/commit/58eb23378f2a376565a66ac32c93a316c45b6131#diff-b3c160475f0fbe8ad50310f92d3534172ba98203387a962b7dc8f4a23b15cf4dL35
Also fix https://github.com/NVIDIA/apex/issues/1048 and https://github.com/NVIDIA/apex/issues/1046
=> fix import container_abcs issue

.gitignore, apex/contrib/csrc/layer_norm/ln_api.cpp, apex/contrib/csrc/layer_norm/ln_bwd_semi_cuda_kernel.cu, apex/contrib/csrc/layer_norm/ln_fwd_cuda_kernel.cu, apex/contrib/csrc/layer_norm/ln_kernel_traits.h, apex/contrib/csrc/layer_norm/utils.cuh, apex/contrib/layer_norm/__init__.py, apex/contrib/layer_norm/layer_norm.py, apex/contrib/test/layer_norm/test_fast_layer_norm.py, setup.py
Provides faster fwd and bwd kernels for LayerNorm, intended for BERT training.
It should serve as dropin replacement (see `apex/contrib/test/layer_norm/test_fast_layer_norm.py` for details):
```
from apex.contrib.layer_norm import FastLayerNorm
fln = FastLayerNorm(hidden_size).cuda()
y = fln(x)
```
Performance for B=32, S=512 on GA100 - current APEX affine LN kernels vs NEW:
[APEX FWD] Time: 0.0751ms Throughput: 895.7822 GB/sec
[APEX BWD] Time: 0.1762ms Throughput: 572.1678 GB/sec
[ NEW FWD] Time: 0.0535ms Throughput: 1258.0318 GB/sec
[ NEW BWD] Time: 0.0866ms Throughput: 1163.4357 GB/sec
=> fast layer norm

apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp, apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb_kernel.cu, apex/contrib/optimizers/distributed_fused_lamb.py
Changes include:
- Remove sync points (e.g. D2H memcpy caused by dtype mismatch between kernel arguments and kernel parameters, .item() from overflow check, masked_select() and masked_scatter() from update norm calculation).
- Enable step_supports_amp_scaling to that optimizer handles gradient un-scaling.
- Add state_dict() and load_state_dict() so that params/grads/moments buffers & step number can be properly saved and restored from checkpoint.
- Parameter reordering to allow more overlap between backward pass and gradient reduction.
=> sync-free Distributed LAMB + parameter reordering

apex/contrib/csrc/groupbn/batch_norm.h, apex/contrib/csrc/groupbn/batch_norm_add_relu.h
This fixes a build issue due to a recent upstream change which removed many `#include <iostream>` lines.
See https://github.com/pytorch/pytorch/issues/63653 for details.
=> include iostream in groupbn/batch_norm headers

apex/contrib/optimizers/distributed_fused_lamb.py
Separates flat param buffer creation and autograd hook creation to allow setting parameter views to the flat buffer in between. Parameter reordering is disabled for this option to make sure QKV GEMM parameters are in order.  
This MR also adds the option to skip allgather to handle it on user side.
=> option to set param views to flat buffer

setup.py
Measured the installation time on DGX1V with the following command. 
```
time pip install --disable-pip-version-check --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--bnp" --global-option="--xentropy" --global-option="--deprecated_fused_adam" --global-option="--deprecated_fused_lamb" --global-option="--fast_multihead_attn" --global-option="--distributed_lamb" --global-option="--fast_layer_norm" --global-option="--transducer" --global-option="--distributed_adam" --global-option="--fmha" --global-option="--fast_bottleneck" -v .
```
```
real    54m8.329s
user    50m54.960s
sys     3m18.272s
```
```
real    38m26.005s
user    55m59.500s
sys     3m47.616s
```
- passing include directories to `CUDAExtension`'s `include_dirs` argument
- removing `-I/path/to/dir` …
=> Enable ninja for all extensions

csrc/layer_norm_cuda_kernel.cu
- THC/THCDeviceUtils.cuh is being removed: https://github.com/pytorch/pytorch/pull/65472
- Currently fused layer norm includes THC/THCDeviceUtils.cuh only for WARP_SHFL but this function is already implemented in https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/aten/src/ATen/cuda/DeviceUtils.cuh#L44
So there's no need to wait 65472
cc @ptrblck @xwang233
=> [fused layer norm] THCDeviceUtils.cuh -> ATen/cuda/DeviceUtils.cuh

apex/contrib/optimizers/fused_lamb.py
There was a typo (`dytpe` instead of `dtype`) in the contrib FusedLamb that would only cause error in cases with FP16 gradients (which are uncommon).
=> Fix typo in contrib FusedLamb.

apex/transformer/functional/fused_softmax.py, tests/L0/run_transformer/test_fused_softmax.py
Unpaired `custom_bwd` causes the failure in the below.
While inputs to some fused kernels that support both bfloat16 and float16 are manually casted if autocast is enabled, but I forgot to remove custom_bwd from fused softmax.
```
@functools.wraps(bwd)
def decorate_bwd(*args, **kwargs):
>       with autocast(args[0]._fwd_used_autocast):
E       AttributeError: 'ScaledUpperTriangMaskedSoftmaxBackward' object has no attribute '_fwd_used_autocast'
```
=> Remove `custom_fwd`/`custom_bwd` from fused softmax

apex/contrib/csrc/groupbn/batch_norm.cu, apex/contrib/csrc/groupbn/batch_norm_add_relu.cu, apex/contrib/csrc/groupbn/ipc.cu
Upstream PyTorch will soon remove this header, and it looks like it is not really used:
https://github.com/pytorch/pytorch/pull/66388
CC @ptrblck
=> remove `THCNumerics.h` includes 

apex/transformer/tensor_parallel/cross_entropy.py, tests/L0/run_transformer/run_cross_entropy_test.py
@erhoo82 proposed this change to avoid using a clone in the cross-entropy function as it incurs extra D2D copy time. Added a test to check for mutation in the loss function/backward.
cc @ptrblck @eqy
=> Use out-of-place to avoid D2D copy in tensor parallel cross entropy

apex/transformer/parallel_state.py
Two misc updates to `parallel_state.py`:
+  `is_rank_in_embedding_group` which appears to be necessary for models like BERT.
+ check that the pipeline-model-parallel world size is greater than 2 when interleaving is enabled (to mirror Megatron constraint):
https://github.com/NVIDIA/Megatron-LM/blob/b31e1296354e979722627a6c4dedafe19b51fa97/megatron/arguments.py#L132
CC @crcrpar @ptrblck
=> Update parallel_state with Megatron pipeline parallel size and embedding rank

apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, tests/L0/run_transformer/run_pipeline_parallel_test.py
The current usage of `get_kth_microbatch` in the tests seems to require identical data for each pipeline stage, which seems unnecessary.
CC @crcrpar
=> Tweak use of batch with `get_kth_microbatch`

apex/transformer/pipeline_parallel/utils.py, tests/L0/run_transformer/run_dynamic_batchsize_test.py, tests/L0/run_transformer/run_pipeline_parallel_test.py
We've seen many bugs due to `get_kth_microbatch` stepping past the number of elements in a minibatch silently. This PR changes the behavior to fire an assert when this happens and fixes a few bugs in tests uncovered by this change.
The batch size increase in the dynamic batch size is to support machines with 16 processes (GPUs), as there seems to be a limitation when the number of pipeline stages (16 GPU * 2 virtual) reaches the number of items in a microbatch (32).
CC @crcrpar @ptrblck
=> Check size of minibatch in `get_kth_microbatch`

apex/__init__.py, apex/transformer/pipeline_parallel/schedules/common.py
=> Check `parallel_state.model_parallel_is_initialized` before printing the number of model's parameters

setup.py
As per title to speed up apex build.
The main change is 
```python
def append_nvcc_threads(nvcc_extra_args):
return nvcc_extra_args + ["--threads", "4"]
```
.
With this, in my local environment, apex build got improved from 15m45s to10m49s.
Build command: `CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6+PTX" CFLAGS="-g0" pip install -q --no-cache-dir --disable-pip-version-check --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--bnp" --global-option="--xentropy" --global-option="--deprecated_fused_adam" --global-option="--deprecated_fused_lamb" --global-option="--fast_multihead_attn" --global-option="--distributed_lamb" --global-option="--fast_layer_norm" --global-option="--transducer" --global-option="--distributed_adam" …
=> Add `--threads 4` to `extra_compile_args["nvcc"]`

tests/L0/run_transformer/run_bert_minimal_test.py, tests/L0/run_transformer/run_gpt_minimal_test.py, tests/L0/run_transformer/test_transformer_module.py
It appears running all L0 tests via `python tests/L0/run_tests.py`... can result in different amounts of GPU memory being available when the minimal BERT test launches. On certain configurations, such as 16GiB V100, this can cause the minimal BERT test to OOM and hang as one or more pipeline stages becomes unresponsive. This generally seems to occur within the first few forward-backward passes (as memory usage is still growing).
This PR reduces the memory footprint of the minimal BERT via smaller global batch sizes and reduced model size, and changes the failure reporting for the BERT test to show when a pipeline stage OOMs. Also includes a minor change to the minimal GPT test to use placeholder data.
CC @crcrpar @ptrblck
=> Reduce OOM potential and report it if it happens in BERT test

apex/transformer/pipeline_parallel/p2p_communication.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/run_pipeline_parallel_test.py, tests/L0/run_transformer/test_transformer_module.py
let users specify dtype for p2p comm taking the possibility of O2 style AMP into account
cc @eqy @ptrblck
=> Add an argument of `dtype` to forward_backward functions to specify the dtype used in p2p comm

apex/contrib/csrc/fmha/src/fmha.h, apex/contrib/csrc/multihead_attn/dropout.cuh, apex/contrib/csrc/multihead_attn/softmax.cuh, apex/contrib/csrc/transducer/transducer_joint_kernel.cu, setup.py
OSS PyTorch moved `ATen/CUDAGeneratorImpl.h` to `ATen/cuda/CUDAGeneratorImpl.h` in https://github.com/pytorch/pytorch/pull/70650. This patch makes apex use the new path if a newer PyTorch package is used.
(This is my first time to create a PR for this repo. Please teach me any rule to send a patch)
=> fix: support new path to CUDAGeneratorImpl.h

setup.py
Following up #1267 
I didn't notice that `transducer_joint_cuda` extension hasn't been built with `generator_flag`.
cc: @shintaro-iwasaki
=> Pass `generator_flag` to `transducer_joint_cuda` extension

apex/normalization/__init__.py, apex/normalization/fused_layer_norm.py, csrc/layer_norm_cuda.cpp, csrc/layer_norm_cuda_kernel.cu, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py, tests/L0/run_test.py
#1271 
Pattern-matched implementation of FusedRMSNorm based on FusedLayerNorm. Tests are passing (needed threshold adjustment for `float16`), awaiting benchmark results and cleanup.
=> FusedRMSNorm/"T5LayerNorm" based on FusedLayerNorm

apex/normalization/fused_layer_norm.py, docs/source/layernorm.rst
Followup to #1274, which left out (correct) documentation
=> fix and generate docs for FusedRMSNorm

apex/normalization/fused_layer_norm.py
This PR adds the the missing epsilon to formula to match the code
------------
It's actually very unlikely that the denominator will ever be zero in this class - unless each input is zero, since this is the root of sum of squares of numbers.
I don't know if it's faster to add epsilon than to check if all inputs are zero, since the output will be zero then.
@eqy
=> [FusedRMSNorm doc] document where epsilon is added

README.md, apex/pyprof/nvtx/nvmarker.py
For those who wonder why `FutureWarning` is used instead of `DeprecationWarning`, see https://docs.python.org/3/library/warnings.html#warning-categories for the details.
cc @ptrblck
=> Deprecate PyProf

apex/reparameterization/__init__.py, apex/reparameterization/weight_norm.py
related #1315
I couldn't find `Fused_Weight_Norm` which is imported in weight_norm.py
cc @ptrblck
=> deprecate reparameterization module

apex/contrib/bottleneck/bottleneck.py
Leaving masks as bool instead of converting them to fp16
=> Leave bottleneck masks as bool

apex/contrib/conv_bias_relu/__init__.py, apex/contrib/conv_bias_relu/conv_bias_relu.py, apex/contrib/csrc/conv_bias_relu/conv_bias_relu.cpp, apex/contrib/test/conv_bias_relu/test_conv_bias_relu.py, setup.py
Port #1332 
* Enabled Conv-Bias-ReLU fusion
The following modules are enabled using cuDNN runtime fusion:
1) Conv-Bias-ReLU (+backward)
2) Conv-Bias (+backward)
3) Conv-Bias-Mask-ReLU (+backward)
* Casts cleanup and autocast in unittest
- Remove redundant dtype casts
- Simulate the usage in the unittest by using torch.cuda.amp.autocast
Co-authored-by: Masaki Kozuki <mkozuki@nvidia.com>
* Fixed save_for_backward
Co-authored-by: Masaki Kozuki <mkozuki@nvidia.com>
Co-authored-by: root <root@luna-0277.selene.nvidia.com>
=> Port #1332 to 22.04 branch

apex/contrib/bottleneck/__init__.py, apex/contrib/bottleneck/bottleneck.py, apex/contrib/bottleneck/bottleneck_module_test.py, apex/contrib/bottleneck/halo_exchangers.py, apex/contrib/csrc/bottleneck/bottleneck.cpp, apex/contrib/csrc/nccl_p2p/nccl_p2p.cpp, apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cu, apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cuh, apex/contrib/csrc/peer_memory/peer_memory.cpp, apex/contrib/csrc/peer_memory/peer_memory_cuda.cu, apex/contrib/csrc/peer_memory/peer_memory_cuda.cuh, apex/contrib/peer_memory/__init__.py, apex/contrib/peer_memory/peer_halo_exchange_module_tests.py, apex/contrib/peer_memory/peer_halo_exchanger_1d.py, apex/contrib/peer_memory/peer_memory.py, setup.py
This PR implements a peer memory pool that ranks can allocate tensors from.
Tensors allocated from the peer memory pool can be accessed from all ranks within a single node.
This PR also implements a push-pull 1d halo exchange kernel that relies on busy waiting on flags in peer memory to synchronize sender and receiver. This way of exchanging halos has very low latency.
=> Peer memory halo exchange

apex/__init__.py, apex/contrib/bottleneck/bottleneck.py, apex/contrib/conv_bias_relu/conv_bias_relu.py, apex/contrib/test/conv_bias_relu/test_conv_bias_relu.py, apex/contrib/test/fmha/test_fmha.py, apex/contrib/test/focal_loss/test_focal_loss.py, setup.py
- Check cuDNN version if `--fast_bottleneck` is specified as it requires cuDNN>=8400.
- Add a comment about the dependency mentioned in https://github.com/NVIDIA/apex/pull/1340#discussion_r841257679.
- Runtime version guard for `apex.contrib.bottleneck` and `apex.contrib.conv_bias_relu`.
If cuDNN doesn't meet the condition, then the following warning will be displayed.
```
#26 112.7     /tmp/pip-req-build-vxkqatsx/setup.py:65: UserWarning: Skip `--fast_bottleneck` as it requires cuDNN 8400 or later, but 8303
#26 112.7       warnings.warn(
#26 112.7     /tmp/pip-req-build-vxkqatsx/setup.py:65: UserWarning: Skip `--fused_conv_bias_relu` as it requires cuDNN 8400 or later, but 8303
#26 112.7       warnings.warn(
```
=> Give Some Extensions Version Guard in Build&Runtime

apex/transformer/testing/commons.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
Added a loss comparison to `test_pipeline_parallel_fwd_bwd.py`.
In order to effectively predict the target loss value, `apex/transformer/testing/commons.py` was also modified to prevent randomization of weights. 
EDIT: 
On second commit I applied some of the suggested changes:
- Reverted the changes in `commons.py`. Instead, the test calls `torch.nn.Module.apply`.
- Minor change in the assertion line.
- Added `get_target_loss` that calculates the loss assuming that `forward_backward_no_pipelining` is correct...
I kept `rank = torch.distributed.get_rank()` because ~~`parallel_state.get_rank_info()` returns something weird...~~ it is easier to debug.
EDIT 2:
- Target loss calculation function is now correct for any size of `pipeline_model_parallel_world_size`.
- Test changed for running on …
=> [WIP] [transformer] add loss comparison to test_pipeline_parallel_fwd_bwd

apex/transformer/pipeline_parallel/p2p_communication.py, apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/run_bert_minimal_test.py, tests/L0/run_transformer/run_gpt_minimal_test.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
(non-interleaved, needs more tests and performance verification)
Current questions:
Does `wait()` need to be respected for `isend` calls? Is there a danger of the underlying memory being repurposed without it?
Why is `torch.cuda.synchronize()` called after `wait()`? Is `wait()` alone not safe enough or is there some issue where CUDA kernel launches aren't serialized?
Follow-up: *Seems important that `torch.cuda.synchronize()` is called _before_ the gather* see also: https://github.com/NVIDIA/Megatron-LM/commit/27fc468964064eeb33b703c9a0b2af938d80dd14
Does the batched `isend`/`irecv` produces reqs that correspond 1:1 with the `P2POp`s?
=> Async pipeline parallel

apex/__init__.py
- https://github.com/NVIDIA/apex/pull/1348
- https://github.com/NVIDIA/apex/issues/1372
```bash
root@89944af7ec95:/opt/pytorch/apex# python -c 'import apex'
root@89944af7ec95:/opt/pytorch/apex# python -c 'import apex.pyprof'
/opt/pytorch/apex/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
```
=> Change the timing of warning

apex/transformer/parallel_state.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, apex/transformer/testing/commons.py, apex/transformer/testing/distributed_test_base.py, tests/L0/run_transformer/run_bert_minimal_test.py, tests/L0/run_transformer/run_gpt_minimal_test.py, tests/L0/run_transformer/test_cross_entropy.py, tests/L0/run_transformer/test_data.py, tests/L0/run_transformer/test_layers.py, tests/L0/run_transformer/test_mapping.py, tests/L0/run_transformer/test_microbatches.py, tests/L0/run_transformer/test_p2p_comm.py, tests/L0/run_transformer/test_parallel_state.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py, tests/L0/run_transformer/test_random.py, tests/L0/run_transformer/test_transformer_module.py, tests/L0/run_transformer/test_transformer_utils.py
This PR enables us to specify `torch.distributed.Backend` for PipelineParallel Process Groups and the other PGs by adding keyword arguments of `"default_backend"` and `"p2p_backend"` to `apex.transformer.parallel_state.initialize_model_parallel`.
By running `tests/L0/run_transformer/run_gpt_minimal_test.py` with various tensor|pipeline parallel size on a node of 8 GPUs, I've verified UCC for Pipeline Parallel PGs and NCCL for any others is functional. NCCL for PP PGs and UCC for the other PGs is not verified and may have bugs, which is why these warnings exist [here](https://github.com/NVIDIA/apex/compare/master...crcrpar:pipelineparallel_ucc_backend?expand=1#diff-bb2dfca8484e986cfb3277f966640c6af6f214aa6f3c5cb713994c72c67f7addR119-R126).
The main changes are in …
=> [transformer] Allow for different backend for Pipeline Parallel ProcessGroups

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
The numerical checks in #1374 assume typical fp32 exact integer range which isn't supported with TF32. This isn't an issue on Volta and earlier but Ampere devices will dispatch to TF32 by default for the linear layers leading to unexpected mismatches.
See also: #1381
CC @crcrpar @Aidyn-A
=> [Pipeline-Parallelism][TF32] Disable TF32 for Pipeline-Parallel numerical checks

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
As noticed by @crcrpar, after the refactor in #1325 the interleaved test was not setting the virtual pipeline pipeline model parallel size which results in interleaving not being fully exercised.
This PR sets the virtual pipeline model parallel size and revises the numerical check to simplify the logic for various configurations as the number of layers per pipeline stage changes with interleaving.
CC @Aidyn-A
=> Test `len(model) > 1` in `test_pipelining_with_interleaving`

apex/transformer/parallel_state.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
=> Do pipeline parallelism tests in double because TF32 environment variables can be painful to manage across test suites

apex/contrib/clip_grad/__init__.py, apex/contrib/clip_grad/clip_grad.py, apex/contrib/test/clip_grad/test_clip_grad.py
I've noticed that gradient clipping is taking a significant amount of runtime in one of my applications, mostly in kernel launch overheads. Fortunately, we already have fused kernels to compute L2 norms for our optimizers. I've just copy-pasted [PyTorch's implementation](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html) and added a special case when the gradients are FP32 or FP16, they are on GPU, and we are computing a 2-norm.
I'm not sure if this is the right place for this, or if we should upstreaming this to PyTorch. In any case, the test passes for me.
=> Gradient clipping with fused kernels

apex/transformer/testing/distributed_test_base.py, requirements.txt
Avoid false-negative comparisions e.g., "470.100.0" < "470.42.0" that happen with string comparison.
CC @crcrpar
=> [UCC][TORCH_UCC]Do integer driver version comparison for UCC

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
This PR adds the following features to `DistributedFusedAdam`:
- Gradient clipping with a sub-set of parameters (for model-parallel parameters)
- Support for [`torch.cuda.amp.GradScaler`](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler)
- Support for models with multiple dtypes and devices
- Option to accumulate gradients in buckets (for accumulating FP16 grads in FP32 buffers)
=> Add features to distributed Adam for Megatron support

apex/contrib/multihead_attn/encdec_multihead_attn_func.py, apex/contrib/multihead_attn/self_multihead_attn_func.py, apex/contrib/test/multihead_attn/test_encdec_multihead_attn.py, apex/contrib/test/multihead_attn/test_self_multihead_attn.py
Fix the arguments of `torch._softmax_backward_data` whose arguments were changed in https://github.com/pytorch/pytorch/pull/66018
Related: #1422
=> [contrib] Fix the reference implementation of multihead_attn

apex/transformer/parallel_state.py, tests/L0/run_transformer/test_parallel_state.py
PR #1416 causes me to experience runtime errors when initializing model-parallel groups for GPT-3 training. I think it is not properly initializing some T5-specific process groups (namely `encoder_relative_position_embedding_ranks`) and passing empty lists to `torch.distributed.new_group`, which is not supported.
This fix allows me to run the NeMo-Megatron GPT-3 implementation (8 V100s, 2-way pipeline, tensor, data parallelism). However, sanity-checking would be appreciated. Pinging @PerkzZheng and @crcrpar.
=> Fix bug when initializing model-parallel process groups for GPT-3

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
This PR has several optimizations to enable good memory scaling in Megatron:
- Add option to allocate gradient buckets out of one large buffer. This makes it easier to access these buffers externally, e.g. for model-parallel communication, at the expense of preventing ZeRO-2 memory scaling.
- Add option to manually initialize params instead of waiting for first backward pass.
- Support param allgathers with any dtype.
- Avoid allocating temporary buffers in side streams, since it made memory pool less efficient.
- When saving state for checkpointing, gather all state on root rank.
- Replace internal dicts with container classes.
The tests pass for me when running on 4 V100s.
=> Improvements in distributed Adam optimizer for Megatron

apex/contrib/csrc/index_mul_2d/index_mul_2d_cuda.cpp, apex/contrib/csrc/index_mul_2d/index_mul_2d_cuda_kernel.cu, apex/contrib/index_mul_2d/__init__.py, apex/contrib/index_mul_2d/index_mul_2d.py, apex/contrib/test/index_mul_2d/test_index_mul_2d.py, setup.py
Index+Mul fusion can bring 1.1X speedup for OC20.
We need port these kernels(fwd, bwd, 2th bwd) to apex.
The kernel is used like this
x_kj = index_mul(x_kj, sbf, idx_kj)
The original code is
x_kj = x_kj[idx_kj] * sbf
The kernels just support Datatype fp32, 1d index, feature size=64 which is only for mlperf OC20 right now. And the input1 and input2 must be 2-dimension tensor, the index must be 1 dimension tensor.
=> add customized fused op index mulitiplication

csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_masked_softmax_cuda.cu
This adds the following features to the softmax fused kernel
1. Full mask support
2. Avoiding in place backward operation as suggested in the Pytorch documentation
Background: The fused kernel outputs uniform distribution When the mask is all 1 (all values are masked). This led to wrong semantics during the backward pass. We implicitly obtain the mask using fwd softmax output (softmax_output == 0) during backward computation. This assumption does not hold true for the corner case of the mask being all 1. This change outputs 0 whenever the mask is all 1. Conceptually, it makes sense to output 0 if you are not attending to any of the keys. We now match PyTorch (non-fused flow) bwd pass with this change for the full mask case.
Fixes: https://github.com/NVIDIA/apex/issues/1430, …
=> support for full mask in fused softmax kernel + avoiding inplace operation in bwd pass

apex/transformer/functional/fused_softmax.py, csrc/megatron/generic_scaled_masked_softmax.cpp, csrc/megatron/generic_scaled_masked_softmax.h, csrc/megatron/generic_scaled_masked_softmax_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_softmax.py
Originally created the PR for NeMo at https://github.com/NVIDIA/NeMo/pull/4594
@ericharper  suggested to move it here
Implemented a generic fused softmax GPU kernel that can be a drop-in replacement of the `FusedScaleMaskSoftmax`. It addresses the following issues:
1. Removed the sequence length limitation. It works with tensor of any length.
2. Fix the `grad_input` modification issue https://github.com/NVIDIA/apex/issues/1430
3. Fix the problem when all keys are masked https://github.com/NVIDIA/apex/issues/1390
It includes a unit test to cover a few cases.
The performance is comparable to the apex one. Here is a training step time graph when it is tested with training a RETRO model.
The blue curve is pytorch softmax. The bottom red curve is apex fused kernel and the middle red curve the …
=> Add a generic fused softmax

apex/mlp/mlp.py, tests/L0/run_mlp/test_mlp.py
to use `torch.testing.assert_close` instead of
`numpy.testing.assert_allclose`. The former uses a bit looser threshold
values.
cc @FDecaYed 
=> Update `apex.mlp` (= `mlp_cuda`) test

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
Checkpointing failed with large models since pickle doesn't support >4 GB byetarrays by default (requires pickle protocol >=4). pickle can handle large PyTorch tensors without problems though. With this change, I've been able to successfully checkpoint GPT-3 175B.
I've also fixed a device mismatch error that I was experiencing because `'cuda' != 'cuda:{device_id}'`. To get around this, I've forced the optimizer device to be in `'cuda:{device_id}'` format.
=> Store distributed Adam state_dict in uint8 tensors

tests/L0/run_fused_layer_norm/test_fused_layer_norm.py, tests/L0/run_mlp/test_mlp.py, tests/L0/run_test.py, tests/L0/run_transformer/test_batch_sampler.py, tests/L0/run_transformer/test_cross_entropy.py, tests/L0/run_transformer/test_fused_softmax.py, tests/L0/run_transformer/test_layers.py, tests/L0/run_transformer/test_mapping.py, tests/L0/run_transformer/test_microbatches.py, tests/L0/run_transformer/test_parallel_state.py, tests/L0/run_transformer/test_random.py, tests/L0/run_transformer/test_transformer_module.py, tests/L0/run_transformer/test_transformer_utils.py
Export junit xml style report only when ~~`xmlrunner` is available and the environment variable of `CI=1`~~ `--xml-report` is passed to `python tests/L0/run_test.py`.
TODO:
of running L0 tests. See the example trace below
```console
======================================================================
Traceback (most recent call last):
File "/home/mkozuki/ghq/github.com/crcrpar/apex/tests/L0/run_test.py", line 91, in <module>
main(args)
File "/home/mkozuki/ghq/github.com/crcrpar/apex/tests/L0/run_test.py", line 78, in main
result = runner.run(suite)
File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/xmlrunner/xmlrunner.py", line 421, in run
result.printErrors()
File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/unittest/runner.py", line 117, in printErrors …
```
=> Use `xmlrunner.XMLTestRunner` accordingly in `tests/L0/run_test.py`

apex/contrib/sparsity/asp.py
Root cause: Torchvision remove APIs that were deprecated before 0.8 (#5386) in 0.12.0
And torchvision.ops.misc.Conv2d is removed, which may cause the failure of ASP lib.
The solution is verified by https://github.com/NVIDIA/apex/issues/1424.
=> [ASP lib] Fix the torchvision.ops.misc.Conv2d error as Torchvision remove deprecated APIs in 0.12.0

apex/contrib/csrc/optimizers/multi_tensor_distopt_adam.cpp, apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu, apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py, csrc/multi_tensor_apply.cuh
While mucking around with the kernels for `DistributedFusedAdam`, I've taken the opportunity to make internal improvements and add new features:
- Refactor kernels so they do not require GPU synchronization.
- Add option to directly use values from params instead of storing a copy of params as optimizer state. I've disabled this by default since NeMo Megatron expects that the optimizer operates on FP32 main params instead of BF16 model params. However, I'd like to enable this option by default in the future since a typical user will use the same dtype for their model and optimizer, so it's an easy memory saving.
- If optimizer is FP32 and params are BF16, add option to just store 16-bit param remainders and reconstruct FP32 params out of BF16 params. This is intended to reduce memory …
=> Optimize distributed Adam kernels and implementation

apex/contrib/optimizers/distributed_fused_lamb.py
This PR adds a guard for `_make_nccl_premul_sum` which had been only available in NGC PyTorch containers as `torch.distributed.make_nccl_premul_sum`
Rel: https://github.com/NVIDIA/apex/issues/1298
=> [contrib] Guard for `torch.distributed._make_nccl_premul_sum`

apex/_autocast_utils.py, apex/mlp/mlp.py, tests/L0/run_mlp/test_mlp.py
- Deify PyTorch autocast context and casts tensors
- add test cases with and without autocast enabled (currently only fp16)
=> Update `apex.mlp` to use fp16 in `autocast`

apex/contrib/test/layer_norm/test_fast_layer_norm.py
=> [contrib][fast_layer_norm] `test_` to `_test_impl` for pytest to not recognize

tests/L0/run_transformer/test_transformer_module.py
especially Bert and GPT scripts are slow sometimes leading to a timeout in CI
=> Introduce `APEX_RUN_SLOW_TESTS` to avoid violating CI timelimit

apex/contrib/optimizers/distributed_fused_adam.py, apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
This PR adds functionality so that the distributed Adam optimizer can overlap grad reduce-scatters with backward compute in the first pipeline stage. Async grad reductions are disabled in the other pipeline stages since it slows down the backward pass, so the reduction should be done externally while waiting for the first stage to finish. Note that this is not compatible with `DistributedDataParallel` since I am not aware of an option to manually trigger a reduction after using `no_sync`.
I've also done some refactoring of distributed Adam to support NeMo-Megatron integration, mostly so that I can selectively disable async grad reductions for model-parallel operations:
- Each bucket independently keeps track of which grads it has received
- Exposed function that creates callback functions …
=> Support overlapped grad sync with Megatron pipeline parallelism

apex/contrib/test/fused_dense/test_fused_dense.py, apex/fused_dense/fused_dense.py
Remove last references to apex amp and replace with torch.autocast, since apex amp is being deprecated according to this issue: https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=3781071&cmtNo=
=> update fused_dense to use torch.autocast instead of apex amp

setup.py
Related: #1498
I verified this by
```
$ docker run -it pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime /bin/bash
<install vim & git>
$ git clone https://github.com/crcrpar/apex -b check_cuda_home_var
$ cd apex
< modify setup.py so that CUDA_HOME is None>
$ root@mkozuki-desktop:/workspace/apex# pip install -v -e .
Using pip 22.1.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
Obtaining file:///workspace/apex
Running command python setup.py egg_info
CUDA_HOME: None
Warning: Torch did not find available GPUs on this system.
If your intention is to cross-compile, this is not an error.
By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
Volta (compute capability 7.0), Turing (compute capability 7.5),
and, if the CUDA version is >= 11.0, Ampere …
```
=> check `CUDA_HOME` before using it

apex/transformer/pipeline_parallel/p2p_communication.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
Optionally disable stream synchronization after batched p2p communication
exported from nvcr.io/nvidia/pytorch:22.09-py3 container with some test cases
cc @eqy @Aidyn-A @ptrblck @Fuzzkatt
=> [transformer] Allow for skipping stream synch

apex/transformer/testing/distributed_test_base.py, tests/L0/run_transformer/test_batch_sampler.py, tests/L0/run_transformer/test_fused_softmax.py
Fixes an OOM issue when running `TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=0 python /opt/pytorch/apex/tests/L0/run_test.py --include run_transformer` on A100x8.
Because `run_test.py` runs all test as a unified suite of all the tests in `run_transformer`. 
https://github.com/NVIDIA/apex/blob/806f9b0f6e321e105029a45f5cbab95f1d6d6434/tests/L0/run_test.py#L82
PyTorch uses the same CUDA cache in most of these tests and the amount of cached memory increases.
But why OOM failure is this happening on A100x8 (cards with the largest memory)? Because `test_fused_softmax` allocates a large amount of memory if a GPU has more than 40GB available:
https://github.com/NVIDIA/apex/blob/806f9b0f6e321e105029a45f5cbab95f1d6d6434/tests/L0/run_transformer/test_fused_softmax.py#L241-L244
The solution is to clear CUDA …
=> Empty CUDA cache in transformer unit tests

apex/contrib/optimizers/distributed_fused_adam.py, apex/transformer/amp/grad_scaler.py
I've gotten incorrect results using distributed Adam to train GPT-3 at FP16 because of a bug with gradient clipping and gradient scaling. In particular, there's an incorrect assumption that gradient clipping is applied before the gradients are unscaled, which results in extremely small gradients. The fix simply requires gradient clipping to handle the case where [`DistributedFusedAdam._grad_scale`](https://github.com/NVIDIA/apex/blob/2c3b8f9a0808e4c931a84def706885ff1d33e5f7/apex/contrib/optimizers/distributed_fused_adam.py#L436) != 1.0. Note that [`torch.cuda.amp.GradScaler.unscale_`](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler.unscale_) does not natively support the distributed optimizer, so I have to unscale by directly manipulating …
=> Fix bug with grad clipping and distributed Adam

apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
This PR makes similar changes as https://github.com/NVIDIA/apex/pull/1475. In particular, it provides an option to pass a custom `no_sync` context into [`apex.transformer.pipeline_parallel.schedules.fwd_bwd_pipelining_with_interleaving._forward_backward_pipelining_with_interleaving`](https://github.com/NVIDIA/apex/blob/2c3b8f9a0808e4c931a84def706885ff1d33e5f7/apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py#L26). In the first pipeline stage, gradient reductions will be overlapped with the final backward pass. In other pipeline stages, the caller is expected to manually perform gradient reductions (in the bubble overhead).
=> Support overlapped grad sync with Megatron interleaved pipeline parallelism

apex/transformer/tensor_parallel/layers.py
Changes the backward pass of the linear layer so that weight gradients for frozen models are not calculated
* Checks if weights have `requires_grad`
* if `requires_grad=False`, only calculate and return the data gradients
* Improves training step time for prompt tuning gpt3 by about 20%
=> Remove weight gradients if model is frozen for linear layer

apex/transformer/functional/fused_softmax.py, csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_softmax.cpp, csrc/megatron/scaled_softmax_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_softmax.py
We updated megatron fused softmax in the following aspects:
1. We updated the limit of sequence length from 2048 to 4096 according to https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/fused_softmax.py#L171
2. We also enabled `mask=None` support in scaled_masked_softmax according to https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/fused_softmax.py#L84
=> Update megatron fused softmax follow megatron-lm

apex/contrib/bottleneck/halo_exchangers.py, apex/contrib/csrc/peer_memory/peer_memory_cuda.cu, apex/contrib/csrc/peer_memory/peer_memory_cuda.cuh, apex/contrib/peer_memory/peer_halo_exchanger_1d.py, apex/contrib/test/bottleneck/test_bottleneck_module.py, apex/contrib/test/peer_memory/test_peer_halo_exchange_module.py
This PR optimizes the peer memory halo exchange to minimize latency:
- Each CUDA thread performs its communication independently, which allows us to avoid cooperative group syncs. With enough threads, we avoid memory fences entirely. The downside is that we can only achieve 50% bandwidth since we pack data and flags into the same communication packets.
- Use an alternating double-buffer scheme, which allows push-only communication.
- The kernel does multiple rounds of communication in the cases where the number of SMs or the peer buffers are too small. This is important since the optimal peer memory requirements have increased by 4x, or more if the tensors are not nicely NHWC.  The only strict requirement is that the peer buffer sizes are aligned to 4096B.
Running on two DGX-1 V100s:
| …
=> Optimize peer memory halo exchange kernel for latency

apex/transformer/testing/commons.py, tests/L0/run_transformer/test_bert_minimal.py, tests/L0/run_transformer/test_dynamic_batchsize.py, tests/L0/run_transformer/test_gpt_minimal.py
The main reason for existence of this PR is that `torch.distributed.<communication>()` without process group being specified (like fixed barriers) can do some nasty things. On single node there are no visible issues whatsoever. However, on multiple nodes with non-IB connections (like Ethernet) the `torch.distributed.<communication>()` hangs causing the timeout-failure. 
Why is this happening on multi node with Ethernet? Because `torch.distributed.<communication>()` attempts to use default PG with NCCL backend over all available ranks. Using all ranks would be only possible if all communications of NCCL were gone through TCP, which we are targeting to avoid by using UCC to do the TCP job.
Please let me know if there are other communications without specified process groups. 
cc @crcrpar …
=> [Transformer] Update test routines

csrc/megatron/scaled_masked_softmax.cpp, csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_upper_triang_masked_softmax.h
This PR includes two commits. One to promote certain integers to long ints so when there are more than 2B elements in the input tensor, the fused softmax doesn't crash. The other commit is to convert non-contiguous input/mask tensors to contiguous format. Currently, the code produces random results when the tensors are non-contiguous.
=> [fused softmax] integer overflow and non-contiguous memory

apex/transformer/pipeline_parallel/utils.py
Return the non-list input to the training function as is. This is to support the per-micro-batch input loader for Megatron Transformer.
=> Return input-loader iterator function in Transformer data loader

apex/RNN/RNNBackend.py, apex/RNN/cells.py, apex/amp/compat.py, apex/contrib/layer_norm/layer_norm.py, apex/contrib/multihead_attn/encdec_multihead_attn.py, apex/contrib/multihead_attn/self_multihead_attn.py, apex/contrib/sparsity/sparse_masklib.py, apex/fused_dense/fused_dense.py, apex/normalization/fused_layer_norm.py
Use  `torch.empty` to initialize tensors instead of `torch.Tensor` which uses the new constructor.
One benefit for this is that we can pass device and dtype directly to  `torch.empty` whereas we can't for `torch.Tensor`
=> replace torch.Tensor with torch.empty

apex/amp/compat.py
Fixes small bug introduced in my last PR https://github.com/NVIDIA/apex/pull/1578
credits to @MozerWang
=> quick fix: torch.empty() must have args

apex/transformer/parallel_state.py
This is to enable the overlap of AMAX reduction and the other DP-communications e.g. gradient reduction and parameter gathering.
=> Use a separate communicator for AMAX reduction

apex/transformer/tensor_parallel/layers.py
Depending on how the forward pass is implemented, grad_output in this function will not be contiguous, so it crashes when calling .view(). By adding this extra line, we ensure it's contiguous. And it's a no-op when it already is contiguous, so performance shouldn't suffer.
=> Update layers.py to ensure grad_output is contiguous

apex/contrib/sparsity/asp.py, apex/contrib/sparsity/permutation_lib.py
Torch.fx can't trace every model; here, the issue is this: https://github.com/pytorch/pytorch/issues/51803
This commit gracefully skips permutations when torch.fx tracing fails, and simply allows ASP to proceed, while still logging the issue seen by torch.fx, unblocking https://github.com/NVIDIA/apex/issues/1590 (used in testing this change).  Networks that can be traced successfully are unaffected by this change.
=> gracefully skipping permutations when torch.fx fails tracing

apex/contrib/conv_bias_relu/__init__.py, apex/contrib/conv_bias_relu/conv_bias_relu.py, apex/contrib/csrc/conv_bias_relu/conv_bias_relu.cpp, apex/contrib/test/conv_bias_relu/test_conv_bias_relu.py
This PR adds ConvFrozenScaleBiasReLU fusion, built on cuDNN runtime fusion for patterns such as 'conv -> frozen batchnorm -> relu'.
=> ConvFrozenScaleBiasReLU fusion

apex/contrib/optimizers/distributed_fused_adam.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py
While running NeMo-Megatron using the distributed optimizer and interleaved pipeline parallelism, we have observed excessive GPU idle time. The root cause is that asynchronous NCCL collectives slow down some GEMMs, so microbatches with overlapped reduce-scatters or all-gathers will take longer and other pipeline-parallel ranks have to wait to receive data. Our current implementation gets the worst-case behavior and the GEMM perf degradation is magnified by the total number of virtual pipeline stages. The fix is for all pipeline-parallel ranks to launch NCCL at the same time, so they're all similarly slowed down and the GEMM perf degradation doesn't compound.
=> Align distopt communication in interleaved pipeline parallelism

apex/optimizers/fused_adam.py, tests/L0/run_optimizers/test_fused_optimizer.py
A Recent update fails for parameter efficient fine-training (PEFT) setup. In this setup, a small subset of params are trained and the rest of the network is frozen. When using PEFT with pipeline parallel mode, it is possible that an entire rank has no trainable params. See this error log:
This PR checks for `len(group['params'])` and defaults to 'cuda' if params are empty.
=> check for empty params in group

apex/contrib/optimizers/distributed_fused_adam.py
When you try overlapping forward compute with distopt param all-gathers, one all-gather is fully exposed. This PR overlaps that all-gather with the optimizer step.
=> Overlap first param sync with optimizer step in distributed Adam

tests/L0/run_transformer/test_bert_minimal.py, tests/L0/run_transformer/test_gpt_minimal.py
Fixes a mismatch between `num_devices` and `world_size` that causes an incorrect setup and subsequently a test failure for 8 GPUs.
=> [Transformer][test/L0] Increase max world_size for BERT and GPT

apex/transformer/pipeline_parallel/p2p_communication.py
There was a change in coalescing manager that affects `batch_isend_irecv` https://github.com/pytorch/pytorch/pull/98793. With this change there will be only one handle (`reqs` is now a single element list) so `_run_p2pops` must be adjusted accordingly. 
cc @crcrpar @ptrblck
=> [Transformer] Update p2p communication routine

apex/normalization/fused_layer_norm.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
Here, we can't use Autograd.Function and Apex nodes when exporting. 
There may be better way to do that - but that at least let onnx.export, torch.jit.script(0 and torch.trace_module() be used. 
We used to replace Apex norm nodes with regular norms in Nemo - better to address at the source.
=> Using regular layernorm for ONNX and TS export

csrc/fused_dense.cpp
when building current code, it will failed for toString() not found, like [issus1645](https://github.com/NVIDIA/apex/issues/1645)
the root cause this problem is:
apex/csrc/fused_dense.cpp:154:72: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
this PR change type() to scalar_type() will fix this
=> current code cannot build due to tensor.type()

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
The test `tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py` is failing in PyTorch container with non-`"YY.MM"` format of `NVIDIA_PYTORCH_VERSION`. This PR adds a workaround by preprocessing the version string.
cc @crcrpar
=> [Test][Transformer] Pre-parse container version

apex/transformer/pipeline_parallel/p2p_communication.py
Transformer tests are failing on UCC because it does not support the latest version of coalescing used in `batch_isend_irecv`:
```
File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1575, in _coalescing_manager
group._start_coalescing(device)
RuntimeError: Backend uccdoes not implement startCoalescing
```
This is a workaround.
=> [Transformer] Do not use batch_isend_irecv for UCC

apex/contrib/optimizers/distributed_fused_adam.py
This PR makes some minor stylistic changes to the distributed Adam optimizer:
- Add type hints for functions and member variables.
- Remove unused functions, mainly the deprecated synchronization logic for async collectives in `GradientBucket.sync_wait` and `ParameterBucket.sync_wait`,
- Make the `ParameterFragment` class a dataclass.
None of these changes should affect functionality.
=> Add type hints to distributed Adam optimizer

tests/L0/run_transformer/test_p2p_comm.py
Running pipeline parallel test on single GPU does not make sense, why not just skip it?
=> [Transformer][Test] Skip UccP2PCommTest on single GPU

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
A major limitation of the distributed optimizer is that checkpointing assumes that the saving and loading models have exactly the same parallel configuration (e.g. the data-parallel size) and optimizer options (e.g. the bucket size). This is because we blindly save and load the model's state, which is sensitive to the bucketing scheme. This PR modifies the format by repacking the optimizer state into per-parameter CPU buffers and discarding the bucket-dependent information . When loading the checkpoint, the optimizer can simply copy from these buffers using its own bucketing scheme.
We do some checks so that checkpoints in the old format can still be loaded (assuming that the parallel config and optimizer options are the same). A simple way to convert an old checkpoint is to load it and …
=> DP-independent checkpoint format for distributed Adam optimizer

tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
Fixes errors in unit test that happened when upset 18 was used.
=> Adjusting test for ONNX opset 18 (now default)

apex/contrib/optimizers/distributed_fused_adam.py
https://github.com/NVIDIA/apex/pull/1704 introduced a bug where the distributed optimizer fails when loading old checkpoints in the deprecated v1 format. This PR includes the checkpoint format in the checkpoint. If the distributed optimizer can't find the format when loading a checkpoint, it falls back to v1. This should help with backwards compatibility if we change the format again in the future.
=> Include format version in distopt checkpoints

apex/contrib/csrc/xentropy/interface.cpp, apex/contrib/csrc/xentropy/xentropy_kernel.cu, apex/contrib/test/xentropy/test_label_smoothing.py, setup.py
`xentropy.__version__` returns `YY.MM.DD` based off of when it's compiled
=> [contrib.xentropy] bfloat16 support

apex/contrib/csrc/layer_norm/ln.h, apex/contrib/csrc/layer_norm/ln_api.cpp, apex/contrib/csrc/layer_norm/ln_bwd_kernels.cuh, apex/contrib/layer_norm/layer_norm.py, apex/contrib/test/layer_norm/test_fast_layer_norm.py, apex/normalization/fused_layer_norm.py, csrc/layer_norm_cuda.cpp, csrc/layer_norm_cuda_kernel.cu, csrc/static_switch.h, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
Hi,
This modifies the fused layernorm/rmsnorm implmentation s.t. the output tensor is saved and the input is supposedly freed. The motivation comes from the observation that the output is going to be saved somewhere anyway. For example, in pre-norm Transformers (GPT, Palm, T5, and many others), the normalization is directly followed by a linear projection either in attention or in mlp.  In post-norm models, the output is additionally used in residual connection directly. However, in both scenarios, the input of the normalization is left unused, making its original usage here pretty redundant as we can save the output tensor that is going to be saved anyway.
We observe a substantial reduction in memory usage when training large transformer models: a 80GB-run on one A100 now only requires …
=> Massively reduce LayerNorm/RMSNorm GPU memory usage in modern networks by tricking torch autograd

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
This PR does some refactoring that will enable distributed optimizer support for FP8 parameters in NeMo. It adds the option to do parameter all-gathers in integer dtypes and adds two member functions - `_check_params_shard_dtypes` and `_param_copy_fragments` - to handle casting into and out of the all-gather buffer. For now these functions will either do a direct cast for floating-point dtypes or copy the most significant bytes for other dtypes. I plan to override these functions in the [NeMo derived class](https://github.com/NVIDIA/NeMo/blob/03465b0d5224a5e82f259d49ba69f2d02b036d94/nemo/core/optim/distributed_adam.py#L51) so that it casts to FP8, performs the all-gather in UINT8, and unpacks into a custom FP8 tensor class.
This PR depends on https://github.com/NVIDIA/apex/pull/1719 and …
=> Distributed optimizer infrastructure for FP8 parameters

apex/contrib/test/fmha/test_fmha.py, apex/contrib/test/transducer/test_transducer_joint.py, apex/contrib/test/transducer/test_transducer_loss.py, tests/L0/run_amp/test_add_param_group.py, tests/L0/run_amp/test_cache.py, tests/L0/run_amp/test_fused_sgd.py, tests/L0/run_amp/test_multi_tensor_l2norm.py, tests/L0/run_amp/test_multi_tensor_unscale_l2norm.py, tests/L0/run_amp/test_multiple_models_optimizers_losses.py
Cleanup so that we have better signal (i.e., are numerical mismatches small or large?) in logs of failing tests.
Some files appear to be mangled because they were in Windows? format somehow? I've converted them to unix in this PR.
CC @crcrpar @Fuzzkatt
=> Cleanup usage of `self.assertTrue(torch.allclose(...`

apex/contrib/csrc/conv_bias_relu/conv_bias_relu.cpp
This PR updates the cuDNN heuristics search to loop through all available engines and find the first successful one for a given operation graph, instead of trying a set number of times.
=> Loop through all available engines for cuDNN heuristics search

apex/transformer/functional/__init__.py, apex/transformer/functional/fused_rope.py, csrc/megatron/fused_rotary_positional_embedding.cpp, csrc/megatron/fused_rotary_positional_embedding.h, csrc/megatron/fused_rotary_positional_embedding_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_rope.py
This is a fused [`apply_rotary_pos_emb`](https://github.com/NVIDIA/Megatron-LM/blob/5f2877d85cb26e47ce6dcdae4b80adf376abf4e8/megatron/core/models/common/embeddings/rotary_pos_embedding.py#L139) implementation for Megatron-Core. 
In my preliminary benchmark, it gives 2x - 4x speedup over the unfused version. `batch_size=2` and `head_num=64` are fixed.
```
dtype=torch.float32, seq_length=2048, hidden_size=128, rotary_percent=0.5
unfused rope: 0.45 ms
fused rope: 0.14 ms
dtype=torch.float32, seq_length=2048, hidden_size=128, rotary_percent=1.0
unfused rope: 0.67 ms
fused rope: 0.15 ms
dtype=torch.float32, seq_length=2048, hidden_size=256, rotary_percent=0.5
unfused rope: 0.84 ms
fused rope: 0.27 ms
dtype=torch.float32, seq_length=2048, hidden_size=256, rotary_percent=1.0
unfused rope: 1.3 ms …
```
=> A fused `apply_rotary_pos_emb` implementation for Megatron-Core

csrc/megatron/fused_rotary_positional_embedding.h, tests/L0/run_transformer/test_fused_rope.py
Fix a bug in the fused rope backward calculation. cc @crcrpar
=> [Bug] Fix a bug in fused rope

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
https://github.com/NVIDIA/apex/pull/1723 added distopt infrastructure to support FP8 parameters in NeMo, but I found a bug with `contiguous_param_buffer=True`. In the non-FP8 case, the local shards of the updated params are views into the contiguous buffer. The Adam kernel outputs to the buffer, we do in-place all-gathers, and the params are ready for fprop. However, the FP8 case should use a temporary buffer since the Adam kernel doesn't support FP8. The Adam kernel outputs to a temporary FP32 buffer and we cast to FP8 in the contiguous param buffer.
=> Distributed optimizer support for contiguous param buffer with FP8 params

apex/transformer/functional/fused_rope.py, csrc/megatron/fused_rotary_positional_embedding.cpp, csrc/megatron/fused_rotary_positional_embedding.h, csrc/megatron/fused_rotary_positional_embedding_cuda.cu, tests/L0/run_transformer/test_fused_rope.py
Support different memory formats to avoid `.contiguous` calls.
=> Avoid `.contiguous()` in fused RoPE

apex/optimizers/fused_adam.py
Getting warnings of the following form:
```
/usr/local/lib/python3.10/dist-packages/apex/optimizers/fused_adam.py:112: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:83.)
self._dummy_overflow_buf = torch.cuda.IntTensor([0])
```
=> Use recommended PyTorch methods to silence warnings

apex/contrib/openfold_triton/_layer_norm_forward_kernels.py, apex/contrib/openfold_triton/fused_adam_swa.py, apex/contrib/test/openfold_triton/test_fused_adam_swa.py
Why?
- FusedAdamSWA interface was loosely typed and error-prone
- The training critical path of FusedAdamSWA (i.e., its step function) could contain unnecessary GPU-host sync when grad_clip_scale is set to a non-CUDA-tensor variable
- FusedAdamSWA didn't have any unit test
What?
- Encapsulated FusedAdamSWA math types and internal numerical type into Python enumerations to improve type robustness and readability
- Accept grad_clip_scale as either a tensor or a number, for the latter case we move it to GPU in a  non-blocking manner to eliminate a GPU-host sync
- Add unit test to guarentee numerical correctness and demostrate usage
=> [contrib] Improve FusedAdamSWA interface and add unit tests

apex/contrib/layer_norm/layer_norm.py, apex/normalization/fused_layer_norm.py
https://github.com/NVIDIA/apex/pull/1715 makes breaking API changes to some fused normalization functions, in particular adding `memory_efficient` as a positional argument. This PR makes `memory_efficient` a keyword argument to ensure backward compatibility.
This change is motivated by the fact that Megatron-LM uses the old API:
https://github.com/NVIDIA/Megatron-LM/blob/2bc6cd307a11423928c675f741e79e03df23e721/megatron/core/fusions/fused_layer_norm.py#L147
This prevents NeMo from upgrading from the 23.09 to 23.11 PyTorch container. See https://github.com/NVIDIA/NeMo/pull/7909#issuecomment-1863754027.
Feedback would be appreciated. An alternative approach is to update Megatron-LM, but this seems simpler. Pinging @RuiWang1998.
=> Make fused normalization functions backward-compatible

csrc/multi_tensor_adam.cu, csrc/multi_tensor_apply.cuh, tests/L0/run_optimizers/test_adam.py
#1654
I think the tests pass without the changes to `multi_tensor_apply.cuh`, but leaving it as-is makes me a bit nervous...
TODOs: graph-capturable Adam, and all other optimizers if people really need 64-bit indexing there...
CC @crcrpar
=> 64-bit indexing Adam

apex/contrib/test/index_mul_2d/test_index_mul_2d.py
failures happen with absolute difference of ~0.001190185546875 and relative diff of ~0.0306854248046875.
=> Increase tolerance to workaround unit test failures on A100

apex/contrib/test/bottleneck/test_bottleneck_module.py
If hw configuration disabled peer memory access, skip the bottleneck tests.
=> Update test_bottleneck_module.py - Skip BottleNeck Peer Memory Test  

tests/L0/run_optimizers/test_adam.py
Memory reserved reaches ~56GiB here so going with 60GiB to be "safe"
=> [64bit indexing][Adam] Add annotation to large tensor test

apex/contrib/test/bottleneck/test_bottleneck_module.py
This PR fixes the errors that would show up if the test_bottleneck_module.py is run on a single GPU platform, where running torch.cuda.can_device_access_peer(0,1) would produce "invalid peer device id".
=> Skip the p2p test on single GPU platforms

apex/contrib/csrc/gpu_direct_storage/gds.cpp, apex/contrib/csrc/gpu_direct_storage/gds.h, apex/contrib/csrc/gpu_direct_storage/gds_pybind.cpp, apex/contrib/examples/gpu_direct_storage/benchmark_load.py, apex/contrib/examples/gpu_direct_storage/benchmark_save.py, apex/contrib/examples/gpu_direct_storage/example_load.py, apex/contrib/examples/gpu_direct_storage/example_save.py, apex/contrib/gpu_direct_storage/README.md, apex/contrib/gpu_direct_storage/__init__.py, setup.py
This is a temporary placeholder for future PyTorch-native GPU Direct Storage until we push it to the upstream.
cc @eqy @Fuzzkatt
=> Add GPUDirect Storage

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
This PR adds basic support for scaled optimizer state as discussed in [the MS-AMP paper](https://arxiv.org/pdf/2310.18313.pdf). The idea is that per-tensor scaling factors along with FP16/FP8 optimizer state results in lower memory usage than FP32 optimizer state with no degradation in convergence. This implementation is not quite the same as the MS-AMP FP8 optimizer since it only uses FP16 optimizer state and uses per-parameter-fragment scaling factors rather than per-parameter. It is a preliminary implementation and its performance could be improved with custom kernels (e.g. kernel to compute scaling factors, fused kernel with FP16-FP32 casts and Adam step).
In the process of debugging, I've also made some other performance optimizations and bugfixes:
- Generalize support for …
=> Support scaled optimizer state in distributed Adam optimizer

tests/L0/run_transformer/test_fused_softmax.py
Workaround for higher mismatches seen on RTX 6000 (Ada)
=> Bump thresholds for `test_backward` in `test_fused_softmax.py`

apex/contrib/optimizers/distributed_fused_adam.py
This PRs aims to move the attributes of `DistributedFusedAdam` to the correct device for v1 state dict.
After loading V1 state dict, tensors in `DistributedFusedAdam.["buckets"]` will be on CPU device when using default checkpoint_io in NeMo.  Although NeMo considers to move the optimizer state to the target CUDA device by the [_optimizer_to_device](https://github.com/Lightning-AI/pytorch-lightning/blob/2.0.7/src/lightning/fabric/utilities/optimizer.py#L31) in `pytorch_lightning`. However, it fails to do what it meant to do for DistributedFusedAdam because tensors like `DistributedFusedAdam.["buckets"][0].param_remainders_shard` would not be moved to the correct device when using the V1 format.
This PR aims to fix it.
=> Move to the correct device for v1 state dict

apex/contrib/csrc/nccl_allocator/NCCLAllocator.cpp, apex/contrib/csrc/nccl_allocator/NCCLAllocator.h, apex/contrib/csrc/nccl_allocator/python_bindings.cpp, apex/contrib/examples/nccl_allocator/allreduce.py, apex/contrib/examples/nccl_allocator/cache.py, apex/contrib/examples/nccl_allocator/change_cuda_allocator.py, apex/contrib/examples/nccl_allocator/toy_ddp.py, apex/contrib/nccl_allocator/README.md, apex/contrib/nccl_allocator/__init__.py, apex/contrib/nccl_allocator/nccl_allocator.py, setup.py
This PR adds a custom pluggable allocator that conditionally utilizes `ncclMemAlloc` and `ncclMemFree` for memory allocations. The buffers allocated through `ncclMemAlloc` can later be registered in NCCL Process Group for a subsequent utilization in Zero-Copy collective communications.
cc @crcrpar @eqy
=> Add nccl_allocator for zero-copy user buffer

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
This PR adds a knob "nccl_ub" in the optimizer to decide whether to use nccl mem allocation and registration (as in this PR: https://github.com/NVIDIA/apex/pull/1796) for DP ReduceScatter communication. When "nccl_ub" is True, the RS output shard buffer will be initialized at the beginning as a whole chunk (just like input buffer) instead of being initialized during the training. This is due to the limitation in NCCL side that NCCL will align to 512MB even when a small buffer is initializated.
=> NCCL userbuffer for DP RS in DistOpt

csrc/type_shim.h
We are seeing numerical mismatches on GH and H100 when running the following unit tests: https://github.com/NVIDIA/apex/blob/master/tests/L0/run_optimizers/test_lamb.py#L251, https://github.com/NVIDIA/apex/blob/master/tests/L0/run_optimizers/test_lamb.py#L315. Running compute sanitizer on these tests reports races:
`root@6b09a87d0bbc:/opt/pytorch/apex/tests/L0/run_optimizers# compute-sanitizer --tool racecheck python test_lamb.py -v -k test_multi_params
========= COMPUTE-SANITIZER
test_multi_params (__main__.TestFusedLAMB) ... ========= Error: Race reported between Read access at T1 reduce_block_into_lanes<float>(T1 *, T1, int, bool)+0x2b0 in /opt/pytorch/apex/csrc/type_shim.h:350
=========     and Write access at T1 reduce_block_into_lanes<float>(T1 *, T1, int, bool)+0x5f0 in …
=> Fix reduce_blocks_into_lanes race condition

tests/L0/run_optimizers/test_lamb.py
Previously various tests in test_lamb.py were using the custom get_max_diff comparison function, which was causing numerical mismatches to appear in CI. This PR updates them to use the much more standard torch.testing.all_close, after which they are cleanly passing CI.
=> Use torch.testing.all_close instead of get_max_diff in test_lamb.py

apex/contrib/conv_bias_relu/conv_bias_relu.py, apex/contrib/layer_norm/layer_norm.py, apex/contrib/test/conv_bias_relu/test_conv_bias_relu.py, apex/contrib/test/cudnn_gbn/test_cudnn_gbn_with_two_gpus.py, apex/contrib/test/layer_norm/test_fast_layer_norm.py, apex/contrib/test/optimizers/test_dist_adam.py, apex/fused_dense/fused_dense.py, apex/normalization/fused_layer_norm.py, apex/transformer/functional/fused_softmax.py, apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/tensor_parallel/layers.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py, tests/L0/run_optimizers/test_adam.py, tests/L0/run_transformer/test_fused_softmax.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py, tests/L1/transformer/pipeline_parallel_fwd_bwd_ucc_async.py
Deprecates usage of torch.cuda.amp across apex codebase
=> deprecate uses of torch.cuda.amp

apex/contrib/optimizers/distributed_fused_adam.py
The distributed optimizer monkey-patches its parameters so that we can register a callback hook whenever a parameter is used in the model, e.g. to perform parameter all-gathers. However, `__torch_function__` has been a class method since PyTorch 1.12 (see https://github.com/pytorch/pytorch/issues/63767), so it does not make sense as a place to launch callbacks for individual parameters. Monkey-patching `__torch_function__` also produces deprecation warnings, which can be annoying.
=> [Distributed optimizer] Do not monkey-patch class methods

apex/contrib/sparsity/permutation_search_kernels/exhaustive_search.py
Apex ASP will generate a cache file called `master_list.pkl` at the root of the working directory and it just looks abrupt.
Change the default behavior to creating a cache directory `.cache` at the root of the working directory and saving/loading the `master_list.pkl` there.
The user can also change the cache directory by setting the environment variable `ASP_CACHE_DIR` in the OS.
=> Allow Configurable Cache Directory

csrc/multi_tensor_apply.cuh
Currently, multi_tensor_apply causes an illegal memory access due to an overflow in the `sizes` field of `TensorListMetadata`. This can be reproduced using the following standalone script:
```python
import torch, amp_C
from apex.multi_tensor_apply import multi_tensor_applier
multi_tensor_adam = amp_C.multi_tensor_adam
size = 2**32+1
g_32 = [torch.zeros(size, dtype=torch.float32, device='cuda')]
p_32 = [torch.zeros(size, dtype=torch.float32, device='cuda')]
m_32 = [torch.zeros(size, dtype=torch.float32, device='cuda')]
v_32 = [torch.zeros(size, dtype=torch.float32, device='cuda')]
_dummy_overflow_buf = torch.zeros(1, dtype=torch.int32, device='cuda')
multi_tensor_applier(multi_tensor_adam, _dummy_overflow_buf, [g_32, p_32, m_32, v_32], 0.0, 0.9, 0.95, 1e-08, 1, 1, 1, 0.1)
print(g_32)
```
=> Fix illegal memory access with multi_tensor_apply size above INT_MAX

apex/transformer/testing/distributed_test_base.py
Pytorch PR https://github.com/pytorch/pytorch/pull/131510 added kwargs `fake_pg` to the function signature of `MultiProcessTestCase._run`. See https://github.com/pytorch/pytorch/blob/19ff9059ebe1f946e65b82fb386ad0d7b6eb69d7/torch/testing/_internal/common_distributed.py#L583-L595 
It's necessary to adapt this change in function signature, otherwise tests may fail, e.g.
```python
root@ced723ee1a16:/opt/pytorch/apex/tests/L0# python run_transformer/test_microbatches.py -v NcclMicrobatchCalculatorTest.test_constant_microbatch_calculator
test_constant_microbatch_calculator (__main__.NcclMicrobatchCalculatorTest) ... INFO:numba.cuda.cudadrv.driver:init
Process process 0:
Traceback (most recent call last):
File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run() …
```
=> Fix DistributedTestBase for transformer distributed tests

apex/contrib/csrc/group_norm/group_norm_nhwc_op.cpp, apex/contrib/group_norm/group_norm.py, apex/contrib/test/group_norm/test_group_norm.py
This PR tries to make GroupNorm can be traced by TorchInductor and don't invoke graph break.
@crcrpar, please take a review, thanks!
=> Traceable GroupNorm

apex/contrib/csrc/optimizers/multi_tensor_distopt_adam.cpp, apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu, apex/contrib/optimizers/distributed_fused_adam.py
Continue of https://github.com/NVIDIA/apex/pull/1794.
This PR enhances distributed fused adam by:
* Support NHWC layout (required by some Conv related models, e.g. Diffusion models);
* Fix the gradient clipping bug;
* Support CUDA graph;
@timmoon10 @crcrpar Please help review, thanks.
=> Enhance Distributed Fused Adam

apex/contrib/optimizers/distributed_fused_adam.py
I've been experiencing some data corruption in distributed optimizer checkpoints because PyTorch is not properly synchronizing the NCCL stream with the main CUDA stream. All indications point to a bug in PyTorch's infrastructure for coalesced NCCL calls and I've isolated it down to cases where we enter [PyTorch's `_coalescing_manager`](https://github.com/pytorch/pytorch/blob/156ca01e51f766b1b069c5c6f3d57112a5c8f9ff/torch/distributed/distributed_c10d.py#L2244) but do not perform any NCCL collectives. The debugger suggests that `_coalescing_manager` sets [this flag](https://github.com/pytorch/pytorch/blob/156ca01e51f766b1b069c5c6f3d57112a5c8f9ff/torch/csrc/distributed/c10d/ProcessGroupNCCL.hpp#L1103) when it enters the context and fails to unset it, resulting in weird behavior in later NCCL …
=> Avoid unnecessary NCCL collective coalescing in distributed optimizer

apex/normalization/fused_layer_norm.py
Using kernel triggers recompilations due to the superfluous guards torch generates for custom kernels. Executing manual implementation should be better
=> [PT2] Normalisation: use manual impl when compiling

apex/contrib/test/group_norm/test_group_norm.py
The grid dim calculations (among others) seem to make assumptions about the minimal number of SMs on a device e.g.,
```
grid.y = std::min(max_blocks_per_grid / blocks_per_slice, params.groups * params.n);
```
This assumption causes `grid.y` to be set to `0` on certain devices with low SM count (10) e.g., A16, A2. Disabling this test for now.
CC @alpha0422 @crcrpar @ptrblck
=> [GroupNorm] Skip GroupNorm tests on A16, A2  etc.,

apex/transformer/testing/distributed_test_base.py
This PR explicitly sets the `destroy_process_group` argument of `run_test` to `False`.
Otherwise, https://github.com/pytorch/pytorch/pull/140820/ adds a default `True` argument to `run_test` which changes the default behavior of `run_test` to destroy the PG, so the subsequent `dist.destroy_process_group()` call in `distributed_test_base.py` does a premature destroy leading to error messages like: 
```
Process process 0:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/apex/transformer/testing/distributed_test_base.py", line 71, in _run
dist.barrier()
File …
```
=> [NCCL] Prevent premature destroy of PGs following PyTorch upstream change

apex/transformer/testing/distributed_test_base.py
This PR updates the previous fix as unfortunately the fix in https://github.com/NVIDIA/apex/pull/1859 was broken by another update to upstream PyTorch which changed the interface for avoiding automatic PG destruction https://github.com/pytorch/pytorch/commit/66476617bf82b4b8ae76b7143fd319a7e456756c
CC @nWEIdia
=> [NCCL] Updated fix for premature destruction of ProcessGroupNCCL

apex/normalization/fused_layer_norm.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
Make non affine ```FusedRMSNorm``` can be traced through by TorchDynamo to provide a better composibility with torch.compile.
cc @crcrpar
=> Traceable RMSNorm part 2: non affine fused rms norm

apex/normalization/fused_layer_norm.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
This PR enables the `LayerNorm` module to be traceable with torch.compile. cc @crcrpar
=> Traceable LayerNorm

README.md, setup.py
Previous Behaviour: extensions are built in series, despite the fact that multiple files in the same extension are compiled in parallel
This pull request adds support for parallel building of multiple extensions. Benchmark results show:
| CPU | Build Parameters | Build Time |
|--|--|--|
| AMD EPYC 24-Core (48 threads) | Original (No optimizations) | 45m29.243s |
| AMD EPYC 24-Core (48 threads) | `--parallel 4` | 12m55.243s |
| AMD EPYC 24-Core (48 threads) | `--parallel 16` | 6m47.962s |
| AMD EPYC 24-Core (48 threads) | `NVCC_APPEND_FLAGS="--threads 8"` | 19m23.878s |
| AMD EPYC 24-Core (48 threads) | `--parallel 4`, `NVCC_APPEND_FLAGS="--threads 8"` | 7m33.151s |
| AMD EPYC 24-Core (48 threads) | `--parallel 16`, `NVCC_APPEND_FLAGS="--threads 8"` | 5m58.479s |
| Intel Xeon 112-Core (224 …
=> build extensions in parallel

apex/contrib/test/multihead_attn/test_self_multihead_attn.py
Adjust threshold due to failure in nvidia internal qa testing on RTX 6000.
=> adjust threshold for test_encdec_multihead_attn.py

apex/contrib/csrc/group_norm_v2/generate_gn_cuda_inst.py, apex/contrib/csrc/group_norm_v2/gn.cpp, apex/contrib/csrc/group_norm_v2/gn.hpp, apex/contrib/csrc/group_norm_v2/gn_cuda.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_host_template.cuh, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_1024_1280.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_1024_1920.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_1024_320.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_1024_640.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_1024_960.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_256_1280.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_256_1920.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_256_2560.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_256_640.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_4096_320.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_4096_640.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_4096_960.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_64_1280.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_inst_64_2560.cu, apex/contrib/csrc/group_norm_v2/gn_cuda_kernel.cuh, apex/contrib/csrc/group_norm_v2/gn_dispatch_hw_c.hpp, apex/contrib/csrc/group_norm_v2/gn_utils.cpp, apex/contrib/csrc/group_norm_v2/gn_utils.hpp, apex/contrib/group_norm/group_norm.py, apex/contrib/test/group_norm/test_group_norm.py, setup.py
GroupNorm v2 outperforms the original GroupNorm extension by utilizing coalesced memory access, tested on B200 with a set of shapes.
=> Add group_norm_v2

apex/contrib/torchsched/__init__.py, apex/contrib/torchsched/config.py, apex/contrib/torchsched/ops/__init__.py, apex/contrib/torchsched/ops/layer_norm.py, apex/contrib/torchsched/passes/__init__.py, apex/contrib/torchsched/passes/pre_grad_passes.py
This PR implements a customized `torch.compile` pass called `pre_grad_custom_pass`, and registers a replacement for PyTorch layer norm with its CuDNN version for better performance automatically.
=> `torch.compile` Pass For Replacing Layer Norm With CuNN Version

apex/contrib/test/group_norm/test_group_norm.py
We should check `counters["graph_break"].total()` instead of `"graph_break" in counters` to determine whether there is any graph break.
The reason that the test **cannot pass the latest PyTorch** (but can pass old versions of PyTorch) is that after https://github.com/pytorch/pytorch/pull/146537 , `counters["graph_break"]` may be visited internally, so the origin `assertNotIn` may fail even if there is no graph breaks.
=> Fix GroupNorm test: properly check graph breaks

apex/contrib/torchsched/__init__.py, apex/contrib/torchsched/backend.py, apex/contrib/torchsched/config.py, apex/contrib/torchsched/inductor/__init__.py, apex/contrib/torchsched/inductor/_utils.py, apex/contrib/torchsched/inductor/event.py, apex/contrib/torchsched/inductor/graph.py, apex/contrib/torchsched/inductor/scheduler.py, apex/contrib/torchsched/inductor/wrapper.py
This PR contains an experimental graph compiler on top of `torch.compile`. We used it for a couple of studies. In this PR we'd like to expose one functionality, which is scheduling independent operators in the graph on multi-streams automatically.
Right now the best use case of it is for small workloads where a single GEMM/Conv can’t fully utilize all the GPU resources, especially during back-propagation.
We achieved 5%-9% E2E performance imporvement for Stable Diffusion with small batch size and full iteration CUDA graph.                                                                       
On importing `apex.contrib.torchsched`, a new `torch.compile` backend `torchsched` is registered:
```python                                                                           
import …
```
=> Graph Compiler For Multi-stream

apex/contrib/test/optimizers/test_distributed_fused_lamb.py
`apex.parallel` was removed in #1896
=> [contrib][DistributedFusedLamb] replace `apex.parallel.flat_dist_call` with coalescing manager in test

apex/contrib/nccl_allocator/nccl_allocator.py
There is a temporary divergence in NVIDIA internal pytorch version related to symmetric memory setting.
This PR handles that divergence.
=> Handle temporary arg name divergence in the torch.cuda.MemPool

apex/contrib/torchsched/__init__.py, apex/contrib/torchsched/backend.py, apex/contrib/torchsched/config.py, apex/contrib/torchsched/inductor/_utils.py, apex/contrib/torchsched/inductor/event.py, apex/contrib/torchsched/inductor/graph.py, apex/contrib/torchsched/inductor/scheduler.py, apex/contrib/torchsched/inductor/wrapper.py, apex/contrib/torchsched/ops/layer_norm.py, apex/contrib/torchsched/passes/pre_grad_passes.py
- Currently the `contrib.torchsched` module sometimes generate incomplete cross-stream dependencies, causing multi-stream execution yield incorrect results on certain cases
- Refactored cross-stream dependency handling logic in `contrib.torchsched` submodule
- Add debug knobs that can skip certain subgraph(s) and dump generated code
=> [contrib/torchsched] Refactor cross-stream dependency handling
