NVIDIA/apex

apex/parallel/distributed.py, examples/imagenet/main.py
Fix pipeline for imagenet so it's fast and validation pass still works.
Fix ddp for "shared_param" option which doesn't do messaging. This option on imagenet is better performing for small batch sizes.
=> DDP fix, imagenet speedup

apex/amp/utils.py, apex/amp/wrap.py
=> amp shouldn't convert CPU tensors

setup.py
flake8 testing of https://github.com/NVIDIA/apex on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./setup.py:50:23: F821 undefined name 'ctypes'
cudart_path = ctypes.util.find_library('cudart')
^
./apex/amp/wrap.py:194:37: F821 undefined name 'hidden'
elif utils.is_fp_tensor(hidden):
^
./apex/amp/wrap.py:195:41: F821 undefined name 'hidden'
new_args.append(cast_fn(hidden))
^
./apex/amp/wrap.py:198:33: F821 undefined name 'hidden'
new_args.append(hidden)
^
4     F821 undefined name 'hidden'
4
```
=> import ctypes for line 51 of setup.py

apex/parallel/distributed.py
Need to remove cuda.stream from trying to get into the checkpoint for DDP
=> Handle set/get state for DDP, remove stream which cant be pickled.

apex/parallel/__init__.py, apex/parallel/distributed.py, examples/imagenet/main.py
A class that's somewhat similar to DDP but has options to manually select when to reduce gradients. Allows users to do multiple iterations while accumulate in gradient before updating.
=> Add reducer class in parallel/distributed.

apex/parallel/distributed.py, examples/imagenet/main.py
Ready to merge after reviewing dict performance, imagenet bitwise accuracy, and bitwise accuracy for Tomasz Gasior's freezing params smoke test.
=> Fix param freezing

apex/optimizers/__init__.py, apex/optimizers/csrc/fused_adam_cuda.cpp, apex/optimizers/csrc/fused_adam_cuda_kernel.cu, apex/optimizers/fp16_optimizer.py, apex/optimizers/fused_adam.py
Adding fp16_optimizer so fused adam can be used in a similar way to apex.fp16_utils
Adding support for parameter groups
Adding support for weight decay( adamW, https://www.fast.ai/2018/07/02/adam-weight-decay/)
Adding support for fused-in clip_grad_norm
Adding automatic parameter flattening
Adding NaN checking for static loss scale and support dynamic loss scaling now
=> WIP: improve fused adam

apex/parallel/__init__.py, apex/parallel/optimized_sync_batchnorm.py, apex/parallel/optimized_sync_batchnorm_kernel.py, csrc/syncbn.cpp, csrc/welford.cu, tests/synced_batchnorm/single_gpu_unit_test.py, tests/synced_batchnorm/two_gpu_unit_test.py
Added kernel to support sync BN for channel last tensor
=> [sync BN nhwc]

apex/fp16_utils/fp16util.py
=> don't convert to float bn with affine=False

tests/run_mixed_adam/test_fp16_optimizer.py
Added unite tests.
Currently there are 3 skipped test corresponding to known broken cases.
All other tests passed.
=> add unit tests for optimizers/fp16_optimizer

csrc/syncbn.cpp, csrc/welford.cu
I'm opening this PR here and I'll put tests in while processing it.
=> allowing syncBN to run with affine = False

apex/amp/handle.py, apex/amp/scaler.py, csrc/scale_check_overflow.cpp, csrc/scale_check_overflow_kernel.cu, setup.py
PRing to see the diffs.  Tests passed locally.
=> Restore fused kernel

apex/amp/_amp_state.py, apex/amp/frontend.py, apex/amp/handle.py, apex/amp/opt.py, apex/amp/scaler.py, apex/fp16_utils/fp16_optimizer.py, examples/imagenet/main_amp.py, tests/L1/common/main_amp.py, tests/L1/common/run_test.sh, tests/L1/cross_product_distributed/run.sh
Reduces multiprocess spam, gives verbosity=0 option.
Also resolving #188 while i'm at it.
=> Route amp print statements through maybe_print

csrc/multi_tensor_apply.cuh, csrc/multi_tensor_scale_kernel.cu
=> fix includes

setup.py
=> Fix typo in setup.py error message on torch version check

apex/amp/lists/torch_overrides.py, apex/amp/utils.py
What it says on the tin. Ran the L0 amp tests.
=> Conditionally run bmm functions in fp16 based on cuda version

apex/amp/frontend.py
Probably related issue: https://github.com/NVIDIA/apex/issues/301
=> raise exception if cudnn is disabled

apex/amp/_process_optimizer.py, tests/L0/run_amp/test_add_param_group.py
=> Support add_param_group

apex/parallel/sync_batchnorm.py
resolves issue #254
Added input casting for pure python implementation, this supports mismatched
input and layer dtype.
=> [SyncBatchNorm update]

apex/parallel/optimized_sync_batchnorm_kernel.py
update input size check to fix github issue #262
update SyncBatchNorm count check so that size 1 input with cross GPU
synchronization runs fine.
=> [syncbn update]

apex/amp/_initialize.py
=> Add backwards compatibility for PyTorch 0.4 for named_buffers

csrc/amp_C_frontend.cpp, csrc/multi_tensor_apply.cuh, csrc/multi_tensor_l2norm_kernel.cu, tests/L0/run_amp/test_multi_tensor_l2norm.py
To enable fused Novograd and BertAdam (LAMB) optimizers.
@thorjohnsen @sharathts
=> Give multi-tensor L2 norm the ability to compute norms per-tensor as well as globally

csrc/multi_tensor_lamb_stage_1.cu, csrc/multi_tensor_lamb_stage_2.cu
Added a separate typename in template (UPD_T) to allow update term to be fp16 independently of what parameter type T is.
=> Add support for fp16 update term (new UPD_T typename in template)

apex/parallel/sync_batchnorm.py, tests/distributed/synced_batchnorm/python_single_gpu_unit_test.py, tests/distributed/synced_batchnorm/unit_test.sh
fixing empty return from python implementation #285 
adding proper test to verify functional correctness for python implementation
=> [sbn update]

csrc/layer_norm_cuda_kernel.cu
hot fix for #411, tests to follow with @thorjohnsen's PR #405. Possibly this fixes #403 (but backward for non-affine fusedLayerNorm won't be fixed until #405 is merged).
=> fix fused layer norm for >65535 batch

csrc/layer_norm_cuda_kernel.cu, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
This PR supercedes #405 with slightly refactored tests and a test for a large batchsize for #411
=> Clean up layer norm tests

apex/normalization/fused_layer_norm.py
=> Multi tensor sgd, cherry pick #400

apex/parallel/__init__.py
=> skip instancenorm in convert_syncbn_model

apex/optimizers/fused_adam.py, tests/L0/run_optimizers/test_adam.py
This PR:
- fixes fused adam import error when not building with cuda extensions
- making separate list for fp16/32, disable
- making fused adam/novograd/lamb consistent
=> Fix issues in fused_dam

apex/parallel/LARC.py
Remove torch.autograd.Variable
=> LARC needs no Variable

apex/contrib/csrc/groupbn/batch_norm.cu, apex/contrib/csrc/groupbn/batch_norm_add_relu.cu, apex/contrib/csrc/groupbn/ipc.cu, apex/contrib/csrc/xentropy/xentropy_kernel.cu, csrc/compat.h, csrc/fused_adam_cuda_kernel.cu, csrc/layer_norm_cuda_kernel.cu, csrc/multi_tensor_apply.cuh, csrc/multi_tensor_l2norm_kernel.cu, csrc/multi_tensor_lamb.cu, csrc/multi_tensor_lamb_stage_1.cu, csrc/multi_tensor_lamb_stage_2.cu, csrc/multi_tensor_novograd.cu, csrc/type_shim.h, csrc/welford.cu, setup.py, tests/docker_extension_builds/run.sh
Builds on major releases and Dockerhub containers from 1.0 to present without deprecation warnings.
=> Fix for #456

apex/amp/_initialize.py
Rather than simply being a function stored as an instance member.
Fixes #552
=> Make the patched optimizer step function a full method

apex/amp/lists/functional_overrides.py
=> add gelu activation to fp32 list

examples/imagenet/main_amp.py
Enable training model with channel last tensors
Requirements:
- Apex installed without --cuda_ext --cpp_ext
- Volta GPU
- CudNN >= 7.603
- Cuda >= 10.1
- Mixed precision training
Example usage:
```
python main_amp.py -a resnet50 --b 224 --workers 16 --channels-last true --opt-level O2 ./data
```
My benchmarks showing steady 22% performance gains of resnet50 and resnext models.
CC: @jjsjann123
=> Channels last support

apex/contrib/optimizers/fp16_optimizer.py, apex/contrib/optimizers/fused_sgd.py
This fixes https://github.com/NVIDIA/apex/issues/703.
`fp32_groups_flat` should be changed to `fp32_groups` due to changes from https://github.com/NVIDIA/apex/pull/657.
=> Fix attribute name mismatch in state_dict() and load_state_dict()

setup.py
build fails after pytorch change extension to use ninja. using abs path for include_dirs seems fix it
=> change include_dirs to abs path

apex/contrib/csrc/multihead_attn/strided_batched_gemm.h, setup.py
=> Fix deprecated calls in multihead_attn and ninja build failure

apex/contrib/optimizers/fused_adam.py
The cuda kernel used by fused-adam was using the default stream
on the default device. The kernel needs use the same device as
the parameter tensor.
Fixed by using context manager to set correct default device. For
the use_mt case, raised an error. Alternatively, the use_mt
case could launch one kernel per cuda device.
Before this change, my model would crash.
The non-contrib version will also need to be fixed.
=> Fix contrib fused_adam to work correctly with multi-GPU

apex/mlp/mlp.py, csrc/mlp.cpp, csrc/mlp_cuda.cu, tests/L0/run_mlp/test_mlp.py
improved backward activation+bias kernel
added proper support for requires_grad
optional bias and activation
sigmoid activation
better tests
=> Improvements to apex.mlp

apex/contrib/optimizers/fused_adam.py, apex/contrib/optimizers/fused_lamb.py, apex/optimizers/fused_adam.py, apex/optimizers/fused_lamb.py, apex/optimizers/fused_novograd.py, apex/reparameterization/__init__.py, apex/reparameterization/weight_norm.py, requirements_dev.txt
Signed-off-by: asears <asears@users.noreply.github.com>
=> Fixes flake8 --select W605 test warnings

apex/contrib/optimizers/__init__.py
=> Remove distributed lamb from __init__.py

apex/contrib/sparsity/asp.py, apex/contrib/sparsity/sparse_masklib.py
Adding comments for 2d pruning: importance and usage and other minor cleanups.
No functional change.
=> 2d masking and sparsity

apex/contrib/multihead_attn/self_multihead_attn_func.py
Currently base MHA (no layer norm) fails in default mode as additive mask option broke it. This PR fixes the bug. Fix is verified by running /apex/contrib/test/multihead_attn/test_self_multihead_attn.py before and after the fix.
=> fix additive mask option failure with base MHA in default mode

setup.py
Thanks @mcarilli for the review. :)
=> Add sm80 for CUDA >= 11

apex/optimizers/fused_sgd.py
=> Make sgd fused optimizer support setting grads to None

apex/contrib/sparsity/README.md, apex/contrib/sparsity/asp.py
Added an outline to illustrate our recommended recipe to obtain a pruned model
=> Update asp readme

examples/imagenet/main_amp.py
=> use reshape instead of view for imagenet example

apex/contrib/csrc/multihead_attn/softmax.h
Apex MHA dropout implementation keeps RNG states in GPU for graph capture.
=> cuda rng changes for graph capture with apex MHA

apex/contrib/csrc/transducer/transducer_joint.cpp, apex/contrib/csrc/transducer/transducer_joint_kernel.cu, apex/contrib/csrc/transducer/transducer_loss.cpp, apex/contrib/csrc/transducer/transducer_loss_kernel.cu, apex/contrib/test/transducer/test_transducer_joint.py, apex/contrib/test/transducer/test_transducer_loss.py, apex/contrib/test/transducer/transducer_ref.py, apex/contrib/transducer/__init__.py, apex/contrib/transducer/transducer.py, setup.py
Check in extensions for transducer
=> Initial check-in of the transducer extensions

apex/optimizers/fused_novograd.py, csrc/multi_tensor_l2norm_kernel.cu, tests/L0/run_optimizers/test_fused_novograd.py, tests/L0/run_optimizers/test_fused_optimizer.py
1. Added unit tests for fused-novograd
2. Fixed issue that noop flag tensor was not on the same device as other tensors.
3. Fixed issue that even with all tensors on the same device, cuda stream is on a different device than tensors.
=> Add unit tests for Fused NovoGrad

apex/contrib/optimizers/distributed_fused_lamb.py
Changes include:
- enable no_copy
- add barrier for SHARP
=> DistributedFusedLAMB: enable no_copy and add barrier for SHARP

csrc/mlp.cpp, csrc/mlp_cuda.cu
=> initial cublaslt support for MLP

csrc/mlp_cuda.cu
=> Fix cublasLt context create/destroy overhead in MLP extension

csrc/mlp_cuda.cu
Fixes compilation issue with cublas version < 11 by selectively compiling for cublasLt for >=11 version only.
=> compile cublasLt code only for cublas >= 11.0

examples/imagenet/main_amp.py, setup.py
=> local_rank fix

apex/contrib/optimizers/distributed_fused_lamb.py
Dear Sir/Madam,
the flat view creation in lazy init stage 2 fails for parameters which are not in canonical torch contiguous format. 
This PR is for addressing this issue. Please test it and let me know if it works. I tested it on my configurations and it works.
Best and thanks
Thorsten
=> wrapper function for flat view creation in _lazy_init_stage2

apex/contrib/bottleneck/bottleneck.py, apex/contrib/csrc/bottleneck/bottleneck.cpp
Creates three functions to compute grad_out1, grad_out1_halo and wgrad2. No need for function to compute wgrad2 halo, this is just a backward data nhwc convolution on input of shape [N,1,W,C] with padding=(0,1) to produce output of shape [N,1,W,C], we have this function in benchmark code already.
=> Add functions to compute grad_out1, grad_out1_halo

apex/contrib/optimizers/distributed_fused_lamb.py
To use full all-reduce instead reduce-scatter & all-reduce, set full_ar=True
=> Add full all-reduce code path for DistributedFusedAdam

apex/contrib/bottleneck/bottleneck.py, apex/contrib/bottleneck/bottleneck_module_test.py, apex/contrib/csrc/bottleneck/bottleneck.cpp
Verified that fprop works correctly.
Fixed wgrad compute and verified that it works correctly.
Fixed dgrad compute, except for one bug, which I will need Deyu's help to solve.
=> Various bug fixes in fused spatial parallel bottleneck block

apex/contrib/bottleneck/bottleneck.py
Fixed a logic bug in wgrad. With that, all tests pass for all shapes.
=> Bug fix in wgrad

apex/contrib/csrc/multihead_attn/layer_norm.h
Follow up of https://github.com/NVIDIA/apex/pull/1173
cc @ptrblck @crcrpar
=> cleanup the missing THCDeviceUtils.cuh header

csrc/layer_norm_cuda_kernel.cu
Basically the same style of fix as #1184.
CC @ptrblck @crcrpar
=> Fix race reported by compute-sanitizer in `cuComputeGradInput`

apex/contrib/optimizers/distributed_fused_lamb.py
This PR fix two problems.
1. remove the weight broadcast in the constructor
Currently there are two weight broadcasts in the code: one in the constructor, and the other in `_lazy_init_stage1`. One of this broadcast is redundant. The fix is to remove the one in the constructor.
2. disable unnecessary allreduces for clip-after-ar
For clip-after-ar, the L2 norm is already obtained through all reduce, therefore there is no need to do a allreduce on `is_finite` and `self._overflow_buf` in `_pipeline_step`
=> minor fix for dist lamb

apex/contrib/csrc/multihead_attn/dropout.h, apex/contrib/csrc/multihead_attn/strided_batched_gemm.h, apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu, apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu, apex/contrib/csrc/transducer/transducer_joint_kernel.cu, apex/contrib/csrc/transducer/transducer_loss_kernel.cu, apex/contrib/csrc/xentropy/xentropy_kernel.cu
Not sure AT_CUDA_CHECK or C10_CUDA_CHECK is preferable.
Ref: https://github.com/pytorch/pytorch/pull/66391
cc @ptrblck
=> Replace `THCudaCheck` with `C10_CUDA_CHECK`

apex/transformer/pipeline_parallel/utils.py
resolves
- https://github.com/NVIDIA/apex/issues/1204
- https://github.com/NVIDIA/apex/issues/1209
- https://github.com/NVIDIA/apex/issues/1208
=> Import `amp_C` iff `multi_tensor_applier.available`

apex/__init__.py, apex/transformer/_data/__init__.py, apex/transformer/_data/_batchsampler.py, apex/transformer/log_util.py, apex/transformer/parallel_state.py, apex/transformer/pipeline_parallel/p2p_communication.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, apex/transformer/pipeline_parallel/utils.py, apex/transformer/testing/commons.py, apex/transformer/testing/global_vars.py, apex/transformer/utils.py, tests/L0/run_transformer/run_dynamic_batchsize_test.py, tests/L0/run_transformer/run_megatron_gpt_pipeline.py, tests/L0/run_transformer/run_pipeline_parallel_test.py, tests/L0/run_transformer/test_transformer_module.py
This PR demonstrates how our pipeline functions can handle `rampup_batch_size`.
The key is rather in how we write `BatchSampler`'s at least for this PR.
=> [POC] Support Megatron-LM's `rampup_batch_size` argument

apex/transformer/__init__.py, apex/transformer/amp/__init__.py, apex/transformer/amp/grad_scaler.py
NeMo has had this custom `GradScaler` but APEX should have this
cc @ptrblck @eqy
=> Port `GradScaler` tailored to Tensor Model Parallel

apex/transformer/testing/standalone_bert.py, apex/transformer/testing/standalone_gpt.py, tests/L0/run_transformer/run_bert_minimal_test.py, tests/L0/run_transformer/run_pipeline_parallel_test.py, tests/L0/run_transformer/test_transformer_module.py
=> minimal bert pipeline parallel test

apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, apex/transformer/testing/standalone_bert.py, apex/transformer/testing/standalone_gpt.py, tests/L0/run_transformer/gpt_scaling_test.py, tests/L0/run_transformer/run_bert_minimal_test.py, tests/L0/run_transformer/run_gpt_minimal_test.py, tests/L0/run_transformer/test_transformer_module.py
=> Minimal gpt pipeline parallel (builds off of minimal_bert_pipeline_parallel) including cpu-offloading

setup.py
=> version guard to use `--threads` option in setup.py

apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py
=> Fix missing `dtype` in `recv_forward`

apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, tests/L0/run_transformer/run_gpt_minimal_test.py, tests/L0/run_transformer/run_pipeline_parallel_test.py
=> Grad scaler

apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, apex/transformer/pipeline_parallel/utils.py, tests/L0/run_transformer/run_bert_minimal_test.py
@eqy hope you're content with this.
=> allow for `None` batch

apex/__init__.py, apex/_autocast_utils.py, apex/transformer/parallel_state.py, tests/L0/run_transformer/run_pipeline_parallel_test.py
- log messages come with PID, filename, and line number
- tiny cosmetic changes in pipeline parallel test
=> small changes in test and logger format

apex/contrib/csrc/multihead_attn/philox.cuh
Adds inline PTX code for faster dropout fusion: the speed of fused FMHA kernel improves from 75 us to 69 us for num_seq=3, seq_length=512 (BERT). Changes are:
-- Inline PTX for 128 bit counter
-- Inline PTX for 32-bit integer multiply with 64-bit output
=> add inline asm 128-bit counter

apex/contrib/optimizers/distributed_fused_lamb.py
Use only subset of gpus to reduce the l2 norm instead of all
=> fix group range to compute l2_norm

apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py
cc: @erhoo82 @ericharper @eqy @ptrblck
=> transformer: Allows for custom sync context in no pipelining forward backward function

apex/contrib/sparsity/README.md, apex/contrib/sparsity/asp.py, apex/contrib/sparsity/permutation_lib.py, apex/contrib/sparsity/permutation_search_kernels/CUDA_kernels/permutation_search_kernels.cu, apex/contrib/sparsity/permutation_search_kernels/CUDA_kernels/structured_sparsity.cu, apex/contrib/sparsity/permutation_search_kernels/__init__.py, apex/contrib/sparsity/permutation_search_kernels/call_permutation_search_kernels.py, apex/contrib/sparsity/permutation_search_kernels/exhaustive_search.py, apex/contrib/sparsity/permutation_search_kernels/permutation_utilities.py, apex/contrib/sparsity/test/checkpointing_test_part1.py, apex/contrib/sparsity/test/checkpointing_test_part2.py, apex/contrib/sparsity/test/checkpointing_test_reference.py, setup.py
Permutation search is the extension to the ASP (Automatic SParsity) lib. It can help to reduce the accuracy drop due to structured sparse pruning.
Have done E2E checking with various TorchVision networks.
- PyTorch >= 1.8.0
- TorchVision >= 0.9.0
Have offline reviewed with @thorjohnsen 
Submit the Pull Request to @thorjohnsen @ptrblck
=> Add the permutation related support as the extension for asp lib.

csrc/multi_tensor_apply.cuh
=> regards channels last 3d as contiguous

apex/transformer/pipeline_parallel/schedules/common.py
=> [transformer] skip `FastLayerNorm`

apex/transformer/pipeline_parallel/schedules/common.py
=> [transformer] Update `build_model` function to support encoder&decoder model

apex/reparameterization/__init__.py, apex/reparameterization/weight_norm.py
=> Revert "deprecate reparameterization module"

apex/transformer/tensor_parallel/layers.py
Warn only when `gradient_accumulation_fusion` is set to `True` but the extension is unavailable.
=> [transformer] Warn only when `gradient_accumulation_fusion` is `True` and `fused_weight_gradient_mlp_cuda` is missing

README.md, examples/docker/Dockerfile
Add `FusedRMSNorm` to `README.md` and make a few other miniscule changes. (Piggybacked on top of @crcrpar's changes)
=> Minor `README.md` edit + docs update from @crcrpar

apex/transformer/parallel_state.py
- Position Embedding global ranks
- Position Embedding groups
- :func:`get_position_embedding_group`
- :func:`is_rank_in_position_embedding_group`
- :func:`get_data_parallel_src_rank`
- :func:`destroy_model_parallel`
=> [transformer] `parallel_state`: Position Embedding

setup.py
Ref: https://github.com/NVIDIA/cudnn-frontend/releases/tag/v0.6.1
=> [submodule update] Bump cudnn-frontend to v0.6.1

apex/transformer/pipeline_parallel/schedules/common.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_with_interleaving.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py
This option was cherry-picked mainly for easier comparison with megatron-lm.
=> [transformer] warn if deallocation is enabled

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
Added a gradient comparison `test_pipeline_parallel_fwd_bwd.py`.
This PR is depends on #1384. 
cc @crcrpar @eqy
=> Add grad check in test pipeline parallel fwd bwd

apex/transformer/parallel_state.py, tests/L0/run_transformer/test_parallel_state.py
support t5 relative position embedding mpu groups.
=> update: mpu for t5 rpe

apex/transformer/functional/fused_softmax.py, tests/L0/run_transformer/test_fused_softmax.py
Signed-off-by: MaximumEntropy <sandeep.subramanian.1@umontreal.ca>
=> Time dimension shape check for fused scale mask softmax kernel

apex/contrib/bottleneck/bottleneck_module_test.py, apex/contrib/bottleneck/halo_exchangers.py, apex/contrib/csrc/nccl_p2p/nccl_p2p.cpp, apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cu, apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cuh, apex/contrib/peer_memory/peer_memory.py
Various bug fixes related to hangs in the halo exchangers.
=> Bug fixes, perf improvements

tests/L0/run_transformer/test_batch_sampler.py, tests/L0/run_transformer/test_cross_entropy.py, tests/L0/run_transformer/test_data.py, tests/L0/run_transformer/test_fused_softmax.py, tests/L0/run_transformer/test_layers.py, tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py, tests/L0/run_transformer/test_random.py
This PR does not introduce any new functionality. These are just cosmetic changes on the unit tests.
=> [transformer] update tests

apex/transformer/functional/fused_softmax.py, apex/transformer/pipeline_parallel/schedules/fwd_bwd_pipelining_without_interleaving.py, apex/transformer/tensor_parallel/layers.py, apex/transformer/tensor_parallel/mappings.py, apex/transformer/utils.py
Changes made to apex to match megatron-lm gpt training perf.
Mainly using `_all_gather_base` and `_reduce_scatter_base`.
A few other minor fixes.
@erhoo82, @crcrpar, for viz.
=> Sequence parallel perf updates

tests/L0/run_transformer/test_fused_softmax.py
ran with RTX 3070 Ti
rel: #1440 
=> [transformer] unittest: less mem consumption for generic softmax

apex/contrib/bottleneck/halo_exchangers.py, apex/contrib/csrc/peer_memory/peer_memory_cuda.cu, apex/contrib/csrc/peer_memory/peer_memory_cuda.cuh, apex/contrib/peer_memory/__init__.py, apex/contrib/peer_memory/peer_halo_exchange_module_tests.py, apex/contrib/peer_memory/peer_halo_exchanger_1d.py
For 2-way spatial parallel case, we only need to exchange halo on one side, since the other side is zeroed. Added this.
Fixed a bug in module test caused by recent change in Pytorch.
=> Fixed peer halo exchange module test

apex/transformer/tensor_parallel/cross_entropy.py, tests/L0/run_transformer/test_cross_entropy.py
Signed-off-by: MaximumEntropy <sandeep.subramanian.1@umontreal.ca>
=> Label smoothing in vocab parallel cross entropy

apex/contrib/csrc/nccl_p2p/nccl_version.cpp, apex/contrib/csrc/nccl_p2p/nccl_version_check.cu, apex/contrib/test/bottleneck/test_bottleneck_module.py, apex/contrib/test/clip_grad/test_clip_grad.py, apex/contrib/test/conv_bias_relu/test_conv_bias_relu.py, apex/contrib/test/cudnn_gbn/test_cudnn_gbn_with_two_gpus.py, apex/contrib/test/fmha/test_fmha.py, apex/contrib/test/focal_loss/test_focal_loss.py, apex/contrib/test/fused_dense/test_fused_dense.py, apex/contrib/test/index_mul_2d/test_index_mul_2d.py, apex/contrib/test/layer_norm/test_fast_layer_norm.py, apex/contrib/test/multihead_attn/test_encdec_multihead_attn.py, apex/contrib/test/multihead_attn/test_encdec_multihead_attn_norm_add.py, apex/contrib/test/multihead_attn/test_fast_self_multihead_attn_bias.py, apex/contrib/test/multihead_attn/test_mha_fused_softmax.py, apex/contrib/test/multihead_attn/test_self_multihead_attn.py, apex/contrib/test/multihead_attn/test_self_multihead_attn_norm_add.py, apex/contrib/test/optimizers/test_dist_adam.py, apex/contrib/test/peer_memory/test_peer_halo_exchange_module.py, apex/contrib/test/transducer/test_transducer_joint.py, apex/contrib/test/transducer/test_transducer_loss.py, apex/contrib/test/xentropy/test_label_smoothing.py, apex/contrib/xentropy/__init__.py, apex/contrib/xentropy/softmax_xentropy.py, setup.py
Also, add `__init__.py` so that we can run contrib tests with `python -m unittest/xmlrunner discover /path/to/apex/contrib/test` (see https://docs.python.org/3/library/unittest.html#test-discovery, https://github.com/xmlrunner/unittest-xml-reporting#command-line). You can specify junit xml report output directory with `-o` option (available only when `xmlrunner` (can be installed with `pip install unittest-xml-reporting`) is selected).
=> Skip test if related contrib modules are not found

apex/contrib/sparsity/permutation_lib.py, apex/contrib/sparsity/sparse_masklib.py
Finish support for Conv1D ops in permutation and mask creation steps.
=> Conv1 d support

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/optimizers/distributed_fused_lamb.py
PyTorch c10d recently introduced some public functions that provides the same functionality as accessing those internals do.
_get_global_rank is deprecated.
c10d._pg_group_ranks is slated for removal as part of some internals refactoring. See https://github.com/pytorch/pytorch/pull/84153 - it will be relanded soon.
=> Replace usage of internal with public APIs

apex/contrib/csrc/fmha/fmha_api.cpp, setup.py
ref:
- https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
- https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-09.html#rel-22-09
cc @ptrblck
=> Update for CUDA 11.8

README.md, apex/RNN/README.md, apex/RNN/models.py, apex/__init__.py, apex/amp/amp.py, apex/amp/frontend.py, apex/fp16_utils/fp16_optimizer.py, apex/fp16_utils/fp16util.py, apex/fp16_utils/loss_scaler.py, apex/parallel/__init__.py, apex/parallel/distributed.py, apex/parallel/sync_batchnorm.py, tests/L0/run_deprecated/test_deprecated_warning.py, tests/L0/run_test.py
Test plan:
cc @ptrblck @eqy @Aidyn-A
=> Deprecate outdated features

apex/transformer/_ucc_util.py
=> Check `is_ucc_available` first for PyTorch < 1.13

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py
=> [transformer][test] update exception message

apex/contrib/optimizers/distributed_fused_adam.py
@erhoo82 observed that the distributed optimizer was not properly overlapping its gradient reductions with the backward compute for certain models. We suspect this is because async NCCL collectives will sometimes serialize the calling stream. We were able to work around this by launching the gradient reductions in a side stream. We've also deferred synchronizing async grad reductions as long as possible if the distributed optimizer has a large, contiguous grad buffer since there would be no memory benefit from eagerly freeing the gradient buffers.
=> Perform dist Adam communication in side stream

apex/transformer/parallel_state.py
This PR adds a missing function that is needed for the interleaved pipeline schedule in https://github.com/NVIDIA/NeMo/pull/5025.
Pinging @ericharper and @erhoo82.
=> Add missing function for interleaved pipeline parallelism

apex/contrib/optimizers/distributed_fused_lamb.py, apex/contrib/test/optimizers/test_distributed_fused_lamb.py
Related: https://github.com/NVIDIA/apex/pull/1534
=> [contrib] fix `reduce_scatter_tensor` fallouts in DistributedFusedLamb

apex/transformer/functional/fused_softmax.py, csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_masked_softmax_cuda.cu, csrc/megatron/scaled_softmax_cuda.cu, csrc/megatron/scaled_upper_triang_masked_softmax.h, csrc/megatron/scaled_upper_triang_masked_softmax_cuda.cu
Signed-off-by: yaoyu-33 <yaoyu.094@gmail.com>
=> Extend softmax fusion seq length to 16384

apex/contrib/csrc/multihead_attn/softmax.cuh, apex/contrib/csrc/multihead_attn/strided_batched_gemm.cuh, apex/contrib/test/multihead_attn/test_encdec_multihead_attn.py, apex/contrib/test/multihead_attn/test_encdec_multihead_attn_norm_add.py, apex/contrib/test/multihead_attn/test_fast_self_multihead_attn_bias.py, apex/contrib/test/multihead_attn/test_mha_fused_softmax.py, apex/contrib/test/multihead_attn/test_self_multihead_attn.py, apex/contrib/test/multihead_attn/test_self_multihead_attn_norm_add.py, setup.py
=> bump cutlass to v2.11.0 for contrib/multihead_attn

apex/contrib/test/optimizers/test_adam.py, apex/optimizers/fused_adam.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_adam.cu, tests/L0/run_optimizers/test_adam.py
This PR adds a "capturable" argument to enable the Adam optimizer to be captured by CUDA graphs. This enhancement also supports non-static LR strategies.
=> Capturable Adam optimizer

apex/contrib/csrc/conv_bias_relu/conv_bias_relu.cpp, apex/contrib/csrc/focal_loss/focal_loss_cuda.cpp, apex/contrib/csrc/index_mul_2d/index_mul_2d_cuda.cpp, apex/contrib/csrc/multihead_attn/additive_masked_softmax_dropout_cuda.cu, apex/contrib/csrc/multihead_attn/multihead_attn_frontend.cpp, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu, apex/contrib/csrc/multihead_attn/strided_batched_gemm.cuh, apex/contrib/csrc/optimizers/fused_adam_cuda.cpp, apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu, apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu, apex/contrib/csrc/xentropy/interface.cpp, apex/contrib/csrc/xentropy/xentropy_kernel.cu, csrc/layer_norm_cuda.cpp, csrc/megatron/generic_scaled_masked_softmax.cpp, csrc/megatron/scaled_masked_softmax.cpp, csrc/megatron/scaled_softmax.cpp, csrc/megatron/scaled_upper_triang_masked_softmax.cpp, setup.py
=> decrease the number of warnings

apex/amp/_amp_state.py, apex/amp/_initialize.py, apex/contrib/clip_grad/clip_grad.py, apex/contrib/sparsity/sparse_masklib.py
rel:
- https://github.com/NVIDIA/apex/issues/1583#issuecomment-1430846880
cc: @xmfbit
=> use `torch.tensor` to create a tensor with initializer values

apex/transformer/parallel_state.py
Add AMAX communicator for the reduction in both TP and DP domains.
=> Single communicator for amax reduction in TP and DP domains

apex/optimizers/fused_adam.py, csrc/amp_C_frontend.cpp, csrc/multi_tensor_adam.cu, tests/L0/run_optimizers/test_adam.py
=> Revert "Add support for FP32 master weights in FusedAdam optimizer"

apex/contrib/csrc/layer_norm/ln.h
=> include stdint.h & stdio.h in fast_layer_norm/ln.h

apex/contrib/test/fused_dense/test_fused_dense.py, csrc/fused_dense.cpp, csrc/fused_dense_cuda.cu
=> add bf16 support for FusedDense

README.md
=> Mention `Ninja` for faster build

apex/contrib/optimizers/distributed_fused_adam.py
PyTorch recently changed their API for coalescing NCCL calls in https://github.com/pytorch/pytorch/pull/98793. This PR adds some hacks so the distributed optimizer supports this change without losing backward compatibility. 
Closes https://github.com/NVIDIA/apex/pull/1660.
=> Update distributed optimizer with new coalescing manager API in PyTorch

apex/transformer/pipeline_parallel/p2p_communication.py
This PR fixes the following failing test cases:
```
test_bert_without_interleaving (test_bert_minimal.UccBertTest)
test_gpt (test_gpt_minimal.UccGptTest)
```
=> [Transformer][UCC] Fix async p2p ops

apex/contrib/test/index_mul_2d/test_index_mul_2d.py
hopefully this would give us some details
cc @eqy
=> Use `torch.testing.assert_close` in test_index_mul_2d.py

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
If **not** set a fit bucket size in the distributed optimizer, memory waste will result. Memory loss is sometimes high but invisible, for example, a 10GB memory penalty for each GPU on a misconfigured gpt-7b. I think reporting a warning when the bucket utilization is low is a solution, and I submitted my code as reference.
=> Add the warning of distributed_fused_adam low bucket usage

apex/contrib/test/openfold_triton/test_openfold_mha.py
add test for openfold triton kernel.
=> add test for openfold triton mha kernel

apex/contrib/test/fmha/test_fmha.py
Fix broken call in #1742
CC @crcrpar
=> Fix `rtol` in `assert_close` cleanup

apex/transformer/pipeline_parallel/p2p_communication.py, tests/docker_extension_builds/run.sh
=> Misc Changes

apex/contrib/openfold_triton/fused_adam_swa.py
This MR is to reduce cpu-gpu interaction for openfold
=> add async copy for openfold swa triton kernel

apex/transformer/functional/__init__.py, apex/transformer/functional/fused_rope.py, csrc/megatron/fused_rotary_positional_embedding.cpp, csrc/megatron/fused_rotary_positional_embedding.h, csrc/megatron/fused_rotary_positional_embedding_cuda.cu, tests/L0/run_transformer/test_fused_rope.py
This is for the packed sequences feature in NeMo.
=> Fused RoPE for `thd` format

apex/contrib/csrc/optimizers/multi_tensor_distopt_adam.cpp, apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu, apex/contrib/optimizers/distributed_fused_adam.py
This PR enhances distributed fused adam by:
1. Support NHWC layout (required by some Conv related models, e.g. Diffusion models);
2. Fix the gradient clipping bug;
3. Support CUDA graph;
@timmoon10 @crcrpar Please help review, thanks.
=> Enhance Distributed Fused Adam

apex/contrib/optimizers/distributed_fused_adam.py, apex/contrib/test/optimizers/test_dist_adam.py
@crcrpar Please take a review and merge, thanks!
=> Add Unittest For Distributed Adam With CUDA Graph

tests/L0/run_test.py
=> remove `run_transformer` from default lists

csrc/mlp.cpp
92a2a9ded22ef20a49e8c31dc2add93b40e8a78c seems related
=> `Tensor.type()` -> `Tensor.scalar_type()`

apex/normalization/fused_layer_norm.py, tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
Make ```FusedRMSNorm``` can be traced through by TorchDynamo to provide a better composibility with ```torch.compile```. If this being accepted, I'll make the rest modules traceable as follow-up PRs.
Similar to https://github.com/NVIDIA/apex/pull/1835
cc @alpha0422 @crcrpar
=> Traceable RMSNorm

tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
torch.onnx.export_to_pretty_string is removed. See also: https://github.com/pytorch/pytorch/pull/137790/files
=> Remove deprecated usage of export_to_pretty_string in apex

apex/contrib/examples/nccl_allocator/allreduce.py, apex/contrib/examples/nccl_allocator/cache.py, apex/contrib/examples/nccl_allocator/change_cuda_allocator.py, apex/contrib/examples/nccl_allocator/toy_ddp.py, apex/contrib/nccl_allocator/nccl_allocator.py, apex/contrib/optimizers/distributed_fused_adam.py
Without the changes in this PR, only one mempool in device 0 gets created in a distributed launch, instead of a mempool per rank.
=> Adds helper API to create pool

apex/contrib/csrc/focal_loss/focal_loss_cuda_kernel.cu
- Main change: Use 8 CTAs per SM instead of 2, which improved perf on B200
- Generalize vectorization (still uses 128-bit)
=> [contrib] Update `apex.contrib.focal_loss` for B200

setup.py
The change is to add SMs accordingly to CUDA version.
=> Support CUDA12.8 in `setup.py`

apex/contrib/optimizers/distributed_fused_adam.py
The dtype of tensor returned by `grad_buffer_view` should be the same as `_grad_buffers`, but it was `param.dtype`. In some cases that grad dtype != param dtype it leads to convergence issue.
=> Fix DistributedFusedAdam for grad dtype != param dtype

apex/contrib/optimizers/distributed_fused_adam.py
DistAdam has a potential performance issue, where if new bucket is full while last communication is still in progress, communication will be delayed after previous communication finish. This is mainly because there's only one CUDA stream for communication, thus NCCL kernels for different buckets are serialized, especially for all-reduce from last bucket and reduce-scatter for new bucket.
In this PR we increase the number of streams for communication, thus to avoid serialization issue.
@crcrpar, could you take a review?
=> Pipeline Reduce-Scatter And All-Reduce In DistAdam
